# Colab GPU pipeline — Final Clean Generalization Protocol

This notebook implements the final experiment design:

1. Create one deterministic train/val/test split from `full_curated_v1`, stratified by `subset`.
2. Train YOLO/RT-DETR on the **training split containing all three training conditions**:
   - `synthetic_drone_positive`
   - `synthetic_distractor_only` / hard negatives
   - `synthetic_drone_plus_distractor` / mixed
3. Evaluate every model separately on the held-out test subsets:
   - `test_drone_positive`
   - `test_hard_negative`
   - `test_mixed`
4. Evaluate GroundingDINO zero-shot on the same test subsets.
5. Save one combined table with `eval_subset` and model metrics.

Important: the hard-negative subset is used as negative training data together with positive drone examples. We do **not** train a standalone detector only on hard negatives.

## Important runtime notes

- Choose **L4 GPU** or **A100 GPU** before running RT-DETR-L. The notebook now stops early if RT-DETR training is enabled on a slow GPU such as T4.
- Training commands now use live streaming output, so epoch progress should appear while the cell is running.
- Training images/labels are copied to local Colab SSD (`/content/...`) by default for speed, but model outputs still save under your Google Drive project folder: `outputs/training/...`. This keeps `.pt` weights safe if the Colab session closes.

In [ ]:
# 1) Configuration, Drive mount, GPU check, helpers
from pathlib import Path
import os
import sys
import subprocess
import shutil
import time
from datetime import datetime

try:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=True)
except Exception as e:
    print("Drive mount failed or not running in Colab:", repr(e))

# Your current Drive project path
DRIVE_PROJECT_PATH = "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification"

PROJECT_ROOT = Path(DRIVE_PROJECT_PATH)
DATASET_ROOT = PROJECT_ROOT / "data/synthetic/full_curated_v1"

# Final clean generalization protocol:
# Train on train split containing positives + hard negatives + mixed.
# Evaluate separately on held-out test_drone_positive, test_hard_negative, test_mixed.
RUN_MODE = "final_clean"

# For final clean, use all split rows by default.
# Set TRAIN_MAX_IMAGES to an integer only for quick debugging.
TRAIN_MAX_IMAGES = None
EVAL_MAX_IMAGES_PER_SUBSET = None

EPOCHS_YOLO = 30
EPOCHS_RTDETR = 5

SPLIT_NAME = "full_curated_v1_final_clean_split"
TRAIN_RATIO, VAL_RATIO, TEST_RATIO = 0.70, 0.15, 0.15

BATCH_YOLO = 16
BATCH_RTDETR = 2  # good for L4; use 1 on T4 if you intentionally train there
IMGSZ = 640

# Speed/stability options.
# Copies training images/labels from Google Drive to Colab's local SSD (/content) before training.
# Training outputs still save to Google Drive under PROJECT_ROOT/outputs/training/...
USE_LOCAL_TRAINING_DATA = True
LOCAL_TRAINING_ROOT = Path("/content/drone_final_clean_training") / SPLIT_NAME

# Safety guard: RT-DETR-L is too slow on T4. Leave True to avoid accidentally repeating the T4 issue.
REQUIRE_FAST_GPU_FOR_RTDETR = True
FAST_GPU_KEYWORDS = ["L4", "A100", "H100"]

BASE_EVAL_CONFIG = "configs/eval_colab_full_curated_v1.yaml"
EVAL_CONFIG_DIR = PROJECT_ROOT / "configs/generated_eval_subsets"
EVAL_OUTPUT_ROOT = PROJECT_ROOT / "outputs/evaluation/final_clean_full_curated_v1"

# Stable run names. The eval config should point to these stable folders.
YOLO_RUN_NAME = "yolo11n_drone_colab"
RTDETR_RUN_NAME = "rtdetr_l_drone_colab"

RUN_GDINO = True
RUN_YOLO_TRAINING = True
RUN_RTDETR_TRAINING = True
RUN_YOLO_INFERENCE = True
RUN_RTDETR_INFERENCE = True

# Set True only when you intentionally want to delete previous training/prediction outputs.
RESET_MODEL_OUTPUTS = False
RESET_PREDICTIONS = True

# Evaluation subsets derived from held-out test rows.
EVAL_SUBSETS = {
    "test_drone_positive": "synthetic_drone_positive",
    "test_hard_negative": "synthetic_distractor_only",
    "test_mixed": "synthetic_drone_plus_distractor",
}

def list_training_runs(root, pattern):
    """Return real Ultralytics run folders that contain weights/best.pt.

    Excludes backup folders created by this notebook, because their names can also match
    patterns like `yolo11n_drone_colab*` and can otherwise be accidentally selected
    as the latest run.
    """
    root = Path(root)
    runs = []
    for p in root.glob(pattern):
        if not p.is_dir():
            continue
        name = p.name.lower()
        if "backup" in name or "old_before_latest_sync" in name or "disabled" in name:
            continue
        if (p / "weights/best.pt").exists():
            runs.append(p)
    return sorted(runs)

def get_latest_training_run(root, pattern):
    """Return the latest real Ultralytics run folder by modification time."""
    runs = list_training_runs(root, pattern)
    if not runs:
        return None
    return max(runs, key=lambda p: p.stat().st_mtime)

def sync_latest_run_to_stable(root, pattern, stable_name):
    """Copy latest Ultralytics run, including suffix folders like -2/-3, to stable_name.

    Why this is needed:
    Ultralytics avoids overwriting existing runs. If `name=yolo11n_drone_colab` already exists,
    a new training run may be saved as `yolo11n_drone_colab-2`, `-3`, etc.
    The evaluation config points to the stable folder `yolo11n_drone_colab`, so this sync step
    prevents evaluation from accidentally using an old checkpoint.
    """
    root = Path(root)
    latest = get_latest_training_run(root, pattern)
    if latest is None:
        print(f"No training runs found for {pattern} under {root}")
        return None

    stable = root / stable_name
    if latest.resolve() == stable.resolve():
        print(f"Stable folder is already latest: {stable}")
        return stable

    backup = root / f"{stable_name}_old_before_latest_sync"
    if backup.exists():
        shutil.rmtree(backup)
    if stable.exists():
        shutil.move(str(stable), str(backup))
        print(f"Backed up old stable folder to: {backup}")

    shutil.copytree(latest, stable)
    print(f"Synced latest run to stable folder:")
    print(f"  latest: {latest}")
    print(f"  stable: {stable}")
    return stable

def format_cmd(cmd):
    return " ".join([repr(str(x)) if " " in str(x) else str(x) for x in cmd])

def run_command(cmd, check=True, cwd=None):
    """Run a command and stream stdout/stderr live.

    This avoids the previous black-box behavior where subprocess.run(capture_output=True)
    hid the training logs until the command ended. It also sets PYTHONUNBUFFERED=1 so
    Python training scripts flush progress sooner.
    """
    cmd = [str(x) for x in cmd]
    print("\nRunning:")
    print(format_cmd(cmd))
    print("\n----- live output starts -----", flush=True)

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"

    start = time.time()
    process = subprocess.Popen(
        cmd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        bufsize=1,
        cwd=str(cwd) if cwd is not None else None,
        env=env,
    )

    assert process.stdout is not None
    for line in process.stdout:
        print(line, end="", flush=True)

    process.wait()
    elapsed_min = (time.time() - start) / 60
    print("\n----- live output ended -----")
    print(f"Return code: {process.returncode}")
    print(f"Elapsed time: {elapsed_min:.1f} minutes")

    if check and process.returncode != 0:
        raise RuntimeError("Command failed. See live output above.")
    return process.returncode

print("CUDA check:")
GPU_NAME = ""
try:
    import torch
    print("CUDA:", torch.cuda.is_available())
    if torch.cuda.is_available():
        GPU_NAME = torch.cuda.get_device_name(0)
        print("GPU:", GPU_NAME)
except Exception as e:
    print("Torch check failed:", repr(e))

if RUN_RTDETR_TRAINING and REQUIRE_FAST_GPU_FOR_RTDETR:
    if not any(k.lower() in GPU_NAME.lower() for k in FAST_GPU_KEYWORDS):
        raise RuntimeError(
            f"RT-DETR training is enabled, but the current GPU is '{GPU_NAME}'.\n"
            f"Choose L4/A100/H100 or set RUN_RTDETR_TRAINING=False.\n"
            f"This guard prevents another silent multi-hour T4 run."
        )

print("\nRun configuration:")
print("RUN_MODE:", RUN_MODE)
print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATASET_ROOT:", DATASET_ROOT)
print("USE_LOCAL_TRAINING_DATA:", USE_LOCAL_TRAINING_DATA)
print("LOCAL_TRAINING_ROOT:", LOCAL_TRAINING_ROOT)
print("SPLIT_NAME:", SPLIT_NAME)
print("TRAIN_MAX_IMAGES:", TRAIN_MAX_IMAGES)
print("EVAL_MAX_IMAGES_PER_SUBSET:", EVAL_MAX_IMAGES_PER_SUBSET)
print("EPOCHS_YOLO:", EPOCHS_YOLO)
print("EPOCHS_RTDETR:", EPOCHS_RTDETR)
print("EVAL_OUTPUT_ROOT:", EVAL_OUTPUT_ROOT)

Mounted at /content/drive
CUDA check:
CUDA: True
GPU: NVIDIA A100-SXM4-80GB

Run configuration:
RUN_MODE: final_clean
PROJECT_ROOT: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification
DATASET_ROOT: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/synthetic/full_curated_v1
USE_LOCAL_TRAINING_DATA: True
LOCAL_TRAINING_ROOT: /content/drone_final_clean_training/full_curated_v1_final_clean_split
SPLIT_NAME: full_curated_v1_final_clean_split
TRAIN_MAX_IMAGES: None
EVAL_MAX_IMAGES_PER_SUBSET: None
EPOCHS_YOLO: 30
EPOCHS_RTDETR: 5
EVAL_OUTPUT_ROOT: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1

In [ ]:
# 2) Verify project and dataset paths
required_paths = [
    PROJECT_ROOT,
    PROJECT_ROOT / "code" / "scripts",
    PROJECT_ROOT / "code" / "src",
    PROJECT_ROOT / "configs",
    PROJECT_ROOT / "requirements-colab.txt",
    DATASET_ROOT / "images",
    DATASET_ROOT / "labels",
    DATASET_ROOT / "metadata.csv",
    PROJECT_ROOT / BASE_EVAL_CONFIG,
]

print("Path checks:")
missing = []
for p in required_paths:
    ok = p.exists()
    print(f"{ok!s:5}  {p}")
    if not ok:
        missing.append(str(p))

if missing:
    raise FileNotFoundError("Missing required paths:\n" + "\n".join(missing))

os.chdir(PROJECT_ROOT)
if str(PROJECT_ROOT / "code" / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "code" / "src"))

print("\nProject and dataset are ready.")

Path checks:
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/requirements-colab.txt
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/synthetic/full_curated_v1/images
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/synthetic/full_curated_v1/labels
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/synthetic/full_curated_v1/metadata.csv
True   /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/eval_colab_full_curated_v1.yaml

Project and dataset are ready.

In [ ]:
# #Now verify that the local /content/... copy exists and that DATA_YAML points to it.
# from pathlib import Path
# import os
# import yaml

# local_root = Path("/content/drone_final_clean_training")

# print("local_root exists:", local_root.exists())
# print("local_root:", local_root)

# print("\nTop-level contents:")
# if local_root.exists():
#     for p in sorted(local_root.iterdir()):
#         print(" -", p)

# split_root = Path("/content/drone_final_clean_training/full_curated_v1_final_clean_split")
# print("\nsplit_root exists:", split_root.exists())
# print("split_root:", split_root)

# print("\nRecursive quick check:")
# for sub in [
#     "images/train",
#     "images/val",
#     "labels/train",
#     "labels/val",
# ]:
#     p = split_root / sub
#     print(f"{sub}: exists={p.exists()}, files={len(list(p.glob('*'))) if p.exists() else 'NA'}")

# yaml_path = split_root / "dataset.yaml"
# print("\ndataset.yaml exists:", yaml_path.exists())
# print("dataset.yaml:", yaml_path)

# if yaml_path.exists():
#     with open(yaml_path, "r") as f:
#         data_yaml = yaml.safe_load(f)
#     print("\ndataset.yaml contents:")
#     print(data_yaml)

#     print("\nImportant path check:")
#     print("path:", data_yaml.get("path"))
#     print("train:", data_yaml.get("train"))
#     print("val:", data_yaml.get("val"))

#     if str(data_yaml.get("path", "")).startswith("/content/"):
#         print("\n✅ GOOD: dataset.yaml points to local Colab storage.")
#     else:
#         print("\n⚠️ WARNING: dataset.yaml does not point to local /content storage.")

local_root exists: False
local_root: /content/drone_final_clean_training

Top-level contents:

split_root exists: False
split_root: /content/drone_final_clean_training/full_curated_v1_final_clean_split

Recursive quick check:
images/train: exists=False, files=NA
images/val: exists=False, files=NA
labels/train: exists=False, files=NA
labels/val: exists=False, files=NA

dataset.yaml exists: False
dataset.yaml: /content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml

In [ ]:
# 3) Optional cleanup of old outputs
# RESET_MODEL_OUTPUTS=False by default, because training takes time.
# If you set it to True, this removes all matching Ultralytics runs, including -2/-3 suffix folders.
if RESET_MODEL_OUTPUTS:
    cleanup_patterns = [
        (PROJECT_ROOT / "outputs/training/yolo", f"{YOLO_RUN_NAME}*"),
        (PROJECT_ROOT / "outputs/training/rtdetr", f"{RTDETR_RUN_NAME}*"),
    ]
    for root, pattern in cleanup_patterns:
        for p in root.glob(pattern):
            print("Removing training run:", p)
            shutil.rmtree(p, ignore_errors=True)

if RESET_PREDICTIONS:
    # Final-clean predictions live under separate output folders for each test subset.
    if EVAL_OUTPUT_ROOT.exists():
        for p in EVAL_OUTPUT_ROOT.glob("*/predictions/*_predictions.csv"):
            print("Removing prediction:", p)
            p.unlink()

print("Cleanup step complete.")

Cleanup step complete.

In [ ]:
# 4) Install dependencies + GroundingDINO
# This cell can take several minutes.
os.chdir(PROJECT_ROOT)

run_command([sys.executable, "-m", "pip", "install", "-q", "-r", str(PROJECT_ROOT / "requirements-colab.txt")])
run_command([sys.executable, "-m", "pip", "install", "-q", "transformers==4.41.2", "tokenizers<0.20"])

(PROJECT_ROOT / "external").mkdir(exist_ok=True)
(PROJECT_ROOT / "weights/groundingdino").mkdir(parents=True, exist_ok=True)

gdino_dir = PROJECT_ROOT / "external/GroundingDINO"
if not gdino_dir.is_dir():
    run_command(["git", "clone", "https://github.com/IDEA-Research/GroundingDINO.git", str(gdino_dir)])

ckpt = PROJECT_ROOT / "weights/groundingdino/groundingdino_swint_ogc.pth"
if not ckpt.is_file():
    run_command([
        "wget", "-q", "-O", str(ckpt),
        "https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth",
    ])

# Patch for newer torch/CUDA builds when needed.
cuda_file = gdino_dir / "groundingdino/models/GroundingDINO/csrc/MsDeformAttn/ms_deform_attn_cuda.cu"
if cuda_file.exists():
    text = cuda_file.read_text()
    text = text.replace("value.type()", "value.scalar_type()")
    text = text.replace("value.scalar_type().is_cuda()", "value.is_cuda()")
    cuda_file.write_text(text)

run_command([sys.executable, "-m", "pip", "install", "--no-build-isolation", "-e", str(gdino_dir)])

# Verify pinned transformers version
import transformers
print("transformers:", transformers.__version__)

Running:
/usr/bin/python3 -m pip install -q -r '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/requirements-colab.txt'

----- live output starts -----
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 4.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 kB 9.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 78.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.2/280.2 kB 32.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.2/256.2 kB 30.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 12.8 MB/s eta 0:00:00

----- live output ended -----
Return code: 0
Elapsed time: 0.1 minutes

Running:
/usr/bin/python3 -m pip install -q transformers==4.41.2 tokenizers<0.20

----- live output starts -----
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 163.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 129.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 51.6 MB/s eta 0:00:00

----- live output ended -----
Return code: 0
Elapsed time: 0.2 minutes

Running:
/usr/bin/python3 -m pip install --no-build-isolation -e '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/external/GroundingDINO'

----- live output starts -----
Obtaining file:///content/drive/MyDrive/Synthetic%20Stress%20Testing%20for%20Skyborne%20Drone%20Identification/external/GroundingDINO
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (2.11.0+cu128)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (0.26.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (4.41.2)
Requirement already satisfied: addict in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (2.4.0)
Requirement already satisfied: yapf in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (0.43.0)
Requirement already satisfied: timm in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (1.0.27)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (2.0.2)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (4.13.0.92)
Requirement already satisfied: supervision>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (0.29.1)
Requirement already satisfied: pycocotools in /usr/local/lib/python3.12/dist-packages (from groundingdino==0.1.0) (2.0.11)
Requirement already satisfied: defusedxml>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from supervision>=0.22.0->groundingdino==0.1.0) (0.7.1)
Requirement already satisfied: matplotlib>=3.6 in /usr/local/lib/python3.12/dist-packages (from supervision>=0.22.0->groundingdino==0.1.0) (3.10.0)
Requirement already satisfied: pillow>=9.4 in /usr/local/lib/python3.12/dist-packages (from supervision>=0.22.0->groundingdino==0.1.0) (11.3.0)
Requirement already satisfied: pydeprecate<0.10,>=0.9 in /usr/local/lib/python3.12/dist-packages (from supervision>=0.22.0->groundingdino==0.1.0) (0.9.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from supervision>=0.22.0->groundingdino==0.1.0) (6.0.3)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.12/dist-packages (from supervision>=0.22.0->groundingdino==0.1.0) (2.32.4)
Requirement already satisfied: scipy>=1.10 in /usr/local/lib/python3.12/dist-packages (from supervision>=0.22.0->groundingdino==0.1.0) (1.16.3)
Requirement already satisfied: tqdm>=4.62.3 in /usr/local/lib/python3.12/dist-packages (from supervision>=0.22.0->groundingdino==0.1.0) (4.67.3)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (from timm->groundingdino==0.1.0) (0.36.2)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from timm->groundingdino==0.1.0) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (3.29.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->groundingdino==0.1.0) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch->groundingdino==0.1.0) (12.8.90)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->groundingdino==0.1.0) (26.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->groundingdino==0.1.0) (2025.11.3)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.12/dist-packages (from transformers->groundingdino==0.1.0) (0.19.1)
Requirement already satisfied: platformdirs>=3.5.1 in /usr/local/lib/python3.12/dist-packages (from yapf->groundingdino==0.1.0) (4.10.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch->groundingdino==0.1.0) (1.5.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub->timm->groundingdino==0.1.0) (1.5.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->supervision>=0.22.0->groundingdino==0.1.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->supervision>=0.22.0->groundingdino==0.1.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->supervision>=0.22.0->groundingdino==0.1.0) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->supervision>=0.22.0->groundingdino==0.1.0) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->supervision>=0.22.0->groundingdino==0.1.0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->supervision>=0.22.0->groundingdino==0.1.0) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26->supervision>=0.22.0->groundingdino==0.1.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26->supervision>=0.22.0->groundingdino==0.1.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26->supervision>=0.22.0->groundingdino==0.1.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26->supervision>=0.22.0->groundingdino==0.1.0) (2026.5.20)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->groundingdino==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->groundingdino==0.1.0) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6->supervision>=0.22.0->groundingdino==0.1.0) (1.17.0)
Installing collected packages: groundingdino
  Running setup.py develop for groundingdino
Successfully installed groundingdino-0.1.0

----- live output ended -----
Return code: 0
Elapsed time: 2.1 minutes
transformers: 4.41.2

In [ ]:
# 5) Verify imports
os.chdir(PROJECT_ROOT)

gdino_path = str(PROJECT_ROOT / "external/GroundingDINO")
src_path = str(PROJECT_ROOT / "code" / "src")
for p in [gdino_path, src_path]:
    if p not in sys.path:
        sys.path.insert(0, p)

import groundingdino
print("GroundingDINO import OK")

from ultralytics import YOLO
print("Ultralytics import OK")

GroundingDINO import OK
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics import OK

In [ ]:
# 6) Create final-clean train / val / test split and Ultralytics dataset.yaml
# Training split contains positives + hard negatives + mixed.
# Evaluation will later be done separately on test_drone_positive, test_hard_negative, test_mixed.

import pandas as pd
import random
from pathlib import Path

metadata_path = DATASET_ROOT / "metadata.csv"
metadata_df = pd.read_csv(metadata_path)

required_cols = {"image_id", "subset"}
missing_cols = required_cols - set(metadata_df.columns)
if missing_cols:
    raise ValueError(f"metadata.csv missing required columns: {missing_cols}")

split_root = PROJECT_ROOT / "data/training" / SPLIT_NAME
split_root.mkdir(parents=True, exist_ok=True)

# Optional cap for quick debugging, stratified by subset.
work_df = metadata_df.copy()
if TRAIN_MAX_IMAGES is not None and TRAIN_MAX_IMAGES < len(work_df):
    parts = []
    per_subset = max(1, TRAIN_MAX_IMAGES // work_df["subset"].nunique())
    for subset, g in work_df.groupby("subset"):
        g = g.sample(frac=1.0, random_state=42)
        parts.append(g.head(per_subset))
    work_df = pd.concat(parts, ignore_index=True)
    if len(work_df) > TRAIN_MAX_IMAGES:
        work_df = work_df.sample(n=TRAIN_MAX_IMAGES, random_state=42).reset_index(drop=True)

# Deterministic split inside every subset.
split_rows = []
rng = random.Random(42)

for subset, g in work_df.groupby("subset"):
    ids = list(g.index)
    rng.shuffle(ids)

    n = len(ids)
    n_train = int(round(n * TRAIN_RATIO))
    n_val = int(round(n * VAL_RATIO))

    train_ids = set(ids[:n_train])
    val_ids = set(ids[n_train:n_train + n_val])

    for idx in ids:
        row = work_df.loc[idx].copy()
        if idx in train_ids:
            row["split_final_clean"] = "train"
        elif idx in val_ids:
            row["split_final_clean"] = "val"
        else:
            row["split_final_clean"] = "test"
        split_rows.append(row)

split_df = pd.DataFrame(split_rows).reset_index(drop=True)

split_csv = split_root / "split_metadata.csv"
split_df.to_csv(split_csv, index=False)

print("Wrote split metadata:", split_csv)
print("\nSplit counts by subset:")
display(pd.crosstab(split_df["subset"], split_df["split_final_clean"]))

# Optionally copy all training/validation/test images and labels to local Colab SSD.
# This avoids slow training caused by repeatedly reading thousands of small files from mounted Google Drive.
if USE_LOCAL_TRAINING_DATA:
    TRAIN_DATASET_ROOT = LOCAL_TRAINING_ROOT
    (TRAIN_DATASET_ROOT / "images").mkdir(parents=True, exist_ok=True)
    (TRAIN_DATASET_ROOT / "labels").mkdir(parents=True, exist_ok=True)

    print("\nCopying training split files to local Colab SSD:")
    print("  from:", DATASET_ROOT)
    print("  to:  ", TRAIN_DATASET_ROOT)
    print("This may take a few minutes, but training should be faster and more stable afterward.")

    copied_images = 0
    copied_labels = 0
    created_empty_labels = 0

    for i, image_id in enumerate(split_df["image_id"].astype(str), start=1):
        src_img = DATASET_ROOT / "images" / image_id
        dst_img = TRAIN_DATASET_ROOT / "images" / image_id
        if not src_img.exists():
            raise FileNotFoundError(f"Missing image: {src_img}")
        if (not dst_img.exists()) or (dst_img.stat().st_size != src_img.stat().st_size):
            dst_img.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src_img, dst_img)
            copied_images += 1

        label_name = Path(image_id).with_suffix(".txt").name
        src_lbl = DATASET_ROOT / "labels" / label_name
        dst_lbl = TRAIN_DATASET_ROOT / "labels" / label_name
        if src_lbl.exists():
            if (not dst_lbl.exists()) or (dst_lbl.stat().st_size != src_lbl.stat().st_size):
                dst_lbl.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src_lbl, dst_lbl)
                copied_labels += 1
        else:
            # Ultralytics supports empty label files for negative images.
            if not dst_lbl.exists():
                dst_lbl.parent.mkdir(parents=True, exist_ok=True)
                dst_lbl.write_text("", encoding="utf-8")
                created_empty_labels += 1

        if i % 500 == 0 or i == len(split_df):
            print(f"  processed {i}/{len(split_df)} files...", flush=True)

    print(f"Local copy complete. copied_images={copied_images}, copied_labels={copied_labels}, created_empty_labels={created_empty_labels}")
else:
    TRAIN_DATASET_ROOT = DATASET_ROOT
    print("\nUsing training data directly from Google Drive:", TRAIN_DATASET_ROOT)

# Create image list files for Ultralytics.
# Labels are inferred from image paths by replacing /images/ with /labels/.
def image_path_for_id(image_id):
    return TRAIN_DATASET_ROOT / "images" / str(image_id)

for split_name in ["train", "val", "test"]:
    rows = split_df[split_df["split_final_clean"] == split_name]
    list_path = split_root / f"{split_name}_images.txt"
    with open(list_path, "w", encoding="utf-8") as f:
        for image_id in rows["image_id"].astype(str):
            p = image_path_for_id(image_id)
            if not p.exists():
                raise FileNotFoundError(f"Missing image: {p}")
            f.write(str(p) + "\n")
    print(f"{split_name}: {len(rows)} images -> {list_path}")

# Dataset YAML for Ultralytics training.
# Even when TRAIN_DATASET_ROOT is local /content, outputs still save to Drive because the training scripts
# are launched from PROJECT_ROOT and use PROJECT_ROOT/outputs/training/... as their project directory.
DATA_YAML = split_root / "dataset.yaml"
yaml_text = f"""# Auto-generated final clean split
path: "{TRAIN_DATASET_ROOT}"
train: "{split_root / 'train_images.txt'}"
val: "{split_root / 'val_images.txt'}"
test: "{split_root / 'test_images.txt'}"
nc: 1
names:
  0: drone
"""
DATA_YAML.write_text(yaml_text, encoding="utf-8")

print("\nDATA_YAML:", DATA_YAML)
print(DATA_YAML.read_text())

# Basic label sanity.
for split_name in ["train", "val", "test"]:
    rows = split_df[split_df["split_final_clean"] == split_name]
    non_empty = 0
    missing = 0
    for image_id in rows["image_id"].astype(str):
        label_path = TRAIN_DATASET_ROOT / "labels" / Path(image_id).with_suffix(".txt").name
        if not label_path.exists():
            missing += 1
        elif label_path.read_text(encoding="utf-8").strip():
            non_empty += 1
    print(f"{split_name}: rows={len(rows)}, non_empty_drone_labels={non_empty}, missing_labels={missing}")

Wrote split metadata: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split/split_metadata.csv

Split counts by subset:

split_final_clean                test  train  val
subset
synthetic_distractor_only         180    840  180
synthetic_drone_plus_distractor   180    840  180
synthetic_drone_positive          180    840  180

Copying training split files to local Colab SSD:
  from: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/synthetic/full_curated_v1
  to:   /content/drone_final_clean_training/full_curated_v1_final_clean_split
This may take a few minutes, but training should be faster and more stable afterward.
  processed 500/3600 files...
  processed 1000/3600 files...
  processed 1500/3600 files...
  processed 2000/3600 files...
  processed 2500/3600 files...
  processed 3000/3600 files...
  processed 3500/3600 files...
  processed 3600/3600 files...
Local copy complete. copied_images=3600, copied_labels=3600, created_empty_labels=0
train: 2520 images -> /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split/train_images.txt
val: 540 images -> /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split/val_images.txt
test: 540 images -> /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split/test_images.txt

DATA_YAML: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split/dataset.yaml
# Auto-generated final clean split
path: "/content/drone_final_clean_training/full_curated_v1_final_clean_split"
train: "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split/train_images.txt"
val: "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split/val_images.txt"
test: "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split/test_images.txt"
nc: 1
names:
  0: drone

train: rows=2520, non_empty_drone_labels=1680, missing_labels=0
val: rows=540, non_empty_drone_labels=360, missing_labels=0
test: rows=540, non_empty_drone_labels=360, missing_labels=0

In [ ]:
from pathlib import Path

for txt_name in ["train_images.txt", "val_images.txt", "test_images.txt"]:
    txt_path = Path("/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split") / txt_name
    print("\n", txt_name)
    print("exists:", txt_path.exists())
    lines = txt_path.read_text().splitlines()[:5]
    for line in lines:
        print(line)

 train_images.txt
exists: True
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_001334.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_002505.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_001497.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_001295.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_002386.png

 val_images.txt
exists: True
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_002938.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_002986.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_001880.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_000936.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_002163.png

 test_images.txt
exists: True
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_003296.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_000729.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_001612.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_003043.png
/content/drone_final_clean_training/full_curated_v1_final_clean_split/images/img_002037.png

In [ ]:
#rewriting the train/val/test .txt files locally so the whole training input is local.
from pathlib import Path
import yaml

LOCAL_SPLIT_ROOT = Path("/content/drone_final_clean_training/full_curated_v1_final_clean_split")
DRIVE_SPLIT_ROOT = Path("/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/training/full_curated_v1_final_clean_split")

for split in ["train", "val", "test"]:
    drive_txt = DRIVE_SPLIT_ROOT / f"{split}_images.txt"
    local_txt = LOCAL_SPLIT_ROOT / f"{split}_images.txt"

    lines = drive_txt.read_text().splitlines()
    new_lines = []

    for line in lines:
        p = Path(line)
        # Keep only the filename and map it to local images/split/
        new_lines.append(str(LOCAL_SPLIT_ROOT / "images" / split / p.name))

    local_txt.write_text("\n".join(new_lines) + "\n")
    print(f"Wrote local {split} txt:", local_txt, "rows:", len(new_lines))

yaml_path = LOCAL_SPLIT_ROOT / "dataset.yaml"

data_yaml = {
    "path": str(LOCAL_SPLIT_ROOT),
    "train": str(LOCAL_SPLIT_ROOT / "train_images.txt"),
    "val": str(LOCAL_SPLIT_ROOT / "val_images.txt"),
    "test": str(LOCAL_SPLIT_ROOT / "test_images.txt"),
    "nc": 1,
    "names": {0: "drone"},
}

with open(yaml_path, "w") as f:
    yaml.safe_dump(data_yaml, f, sort_keys=False)

DATA_YAML = yaml_path

print("\n✅ Local dataset.yaml ready:")
print(DATA_YAML)
print(yaml_path.read_text())

Wrote local train txt: /content/drone_final_clean_training/full_curated_v1_final_clean_split/train_images.txt rows: 2520
Wrote local val txt: /content/drone_final_clean_training/full_curated_v1_final_clean_split/val_images.txt rows: 540
Wrote local test txt: /content/drone_final_clean_training/full_curated_v1_final_clean_split/test_images.txt rows: 540

✅ Local dataset.yaml ready:
/content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml
path: /content/drone_final_clean_training/full_curated_v1_final_clean_split
train: /content/drone_final_clean_training/full_curated_v1_final_clean_split/train_images.txt
val: /content/drone_final_clean_training/full_curated_v1_final_clean_split/val_images.txt
test: /content/drone_final_clean_training/full_curated_v1_final_clean_split/test_images.txt
nc: 1
names:
  0: drone

In [ ]:
#verify
print("DATA_YAML:", DATA_YAML)
print(Path(DATA_YAML).read_text())

DATA_YAML: /content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml
path: /content/drone_final_clean_training/full_curated_v1_final_clean_split
train: /content/drone_final_clean_training/full_curated_v1_final_clean_split/train_images.txt
val: /content/drone_final_clean_training/full_curated_v1_final_clean_split/val_images.txt
test: /content/drone_final_clean_training/full_curated_v1_final_clean_split/test_images.txt
nc: 1
names:
  0: drone

In [ ]:
# 7) Create held-out evaluation subset datasets and generated eval configs
# Each eval subset contains only TEST rows from one condition:
# - test_drone_positive
# - test_hard_negative
# - test_mixed

import yaml
import pandas as pd
from pathlib import Path
import shutil
import os

split_root = PROJECT_ROOT / "data/training" / SPLIT_NAME
split_df = pd.read_csv(split_root / "split_metadata.csv")

eval_dataset_root = PROJECT_ROOT / "data/evaluation/final_clean_full_curated_v1"
eval_dataset_root.mkdir(parents=True, exist_ok=True)
EVAL_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
EVAL_OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

def copy_or_link(src, dst):
    """Try symlink first; fallback to copy. Google Drive sometimes behaves better with copies."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        return
    try:
        os.symlink(src, dst)
    except Exception:
        shutil.copy2(src, dst)

def replace_strings(obj, replacements):
    """Recursively replace string fragments in a loaded YAML object."""
    if isinstance(obj, dict):
        return {k: replace_strings(v, replacements) for k, v in obj.items()}
    if isinstance(obj, list):
        return [replace_strings(v, replacements) for v in obj]
    if isinstance(obj, str):
        s = obj
        for old, new in replacements.items():
            s = s.replace(old, new)
        return s
    return obj

def make_eval_subset_dataset(eval_name, subset_value):
    rows = split_df[
        (split_df["split_final_clean"] == "test") &
        (split_df["subset"] == subset_value)
    ].copy()

    if EVAL_MAX_IMAGES_PER_SUBSET is not None:
        rows = rows.head(EVAL_MAX_IMAGES_PER_SUBSET).copy()

    subset_root = eval_dataset_root / eval_name
    images_dir = subset_root / "images"
    labels_dir = subset_root / "labels"
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)

    for image_id in rows["image_id"].astype(str):
        src_img = DATASET_ROOT / "images" / image_id
        src_lbl = DATASET_ROOT / "labels" / Path(image_id).with_suffix(".txt").name
        dst_img = images_dir / image_id
        dst_lbl = labels_dir / Path(image_id).with_suffix(".txt").name

        if not src_img.exists():
            raise FileNotFoundError(src_img)
        copy_or_link(src_img, dst_img)

        # Hard negatives should have empty labels; if label is missing, create empty file.
        if src_lbl.exists():
            copy_or_link(src_lbl, dst_lbl)
        else:
            dst_lbl.write_text("", encoding="utf-8")

    rows.to_csv(subset_root / "metadata.csv", index=False)
    return subset_root, rows

def make_eval_config(eval_name, subset_root):
    base_path = PROJECT_ROOT / BASE_EVAL_CONFIG
    cfg = yaml.safe_load(base_path.read_text(encoding="utf-8"))

    # Keep paths relative to PROJECT_ROOT when possible, because scripts receive --project-root.
    rel_subset_root = subset_root.relative_to(PROJECT_ROOT).as_posix()
    rel_output_root = (EVAL_OUTPUT_ROOT / eval_name).relative_to(PROJECT_ROOT).as_posix()

    replacements = {
        "data/synthetic/full_curated_v1": rel_subset_root,
        "outputs/evaluation/colab_full_curated_v1": rel_output_root,
        "outputs/evaluation/full_curated_v1": rel_output_root,
    }
    cfg = replace_strings(cfg, replacements)

    # Patch common schema keys explicitly if present.
    if isinstance(cfg, dict):
        for key in ["dataset_root", "data_root", "root"]:
            if key in cfg and isinstance(cfg[key], str):
                cfg[key] = rel_subset_root
        if "dataset" in cfg and isinstance(cfg["dataset"], dict):
            for key in ["root", "dataset_root", "data_root"]:
                if key in cfg["dataset"]:
                    cfg["dataset"][key] = rel_subset_root
            for key in ["metadata", "metadata_path"]:
                if key in cfg["dataset"]:
                    cfg["dataset"][key] = f"{rel_subset_root}/metadata.csv"
        for key in ["output_dir", "output_root"]:
            if key in cfg:
                cfg[key] = rel_output_root
        if "evaluation" in cfg and isinstance(cfg["evaluation"], dict):
            for key in ["output_dir", "output_root"]:
                if key in cfg["evaluation"]:
                    cfg["evaluation"][key] = rel_output_root

    out_config = EVAL_CONFIG_DIR / f"eval_{eval_name}.yaml"
    out_config.write_text(yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True), encoding="utf-8")
    return out_config

EVAL_JOBS = {}

for eval_name, subset_value in EVAL_SUBSETS.items():
    subset_root, rows = make_eval_subset_dataset(eval_name, subset_value)
    cfg_path = make_eval_config(eval_name, subset_root)
    EVAL_JOBS[eval_name] = {
        "subset": subset_value,
        "dataset_root": subset_root,
        "config": cfg_path,
        "output_root": EVAL_OUTPUT_ROOT / eval_name,
        "n_images": len(rows),
        "n_target_present": int(rows["target_present"].astype(bool).sum()) if "target_present" in rows.columns else None,
    }

print("Created evaluation jobs:")
for name, job in EVAL_JOBS.items():
    print("\n", name)
    for k, v in job.items():
        print(" ", k, ":", v)

print("\nTest counts:")
display(pd.DataFrame([
    {"eval_subset": name, **{k: str(v) for k, v in job.items() if k != "config"}}
    for name, job in EVAL_JOBS.items()
]))

print("\nExample generated config:")
first_cfg = next(iter(EVAL_JOBS.values()))["config"]
print(first_cfg)
print(first_cfg.read_text()[:2000])

Created evaluation jobs:

 test_drone_positive
  subset : synthetic_drone_positive
  dataset_root : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/evaluation/final_clean_full_curated_v1/test_drone_positive
  config : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml
  output_root : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive
  n_images : 180
  n_target_present : 180

 test_hard_negative
  subset : synthetic_distractor_only
  dataset_root : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/evaluation/final_clean_full_curated_v1/test_hard_negative
  config : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml
  output_root : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative
  n_images : 180
  n_target_present : 0

 test_mixed
  subset : synthetic_drone_plus_distractor
  dataset_root : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/evaluation/final_clean_full_curated_v1/test_mixed
  config : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml
  output_root : /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed
  n_images : 180
  n_target_present : 180

Test counts:

,eval_subset,subset,dataset_root,output_root,n_images,n_target_present
0,test_drone_positive,synthetic_drone_positive,/content/drive/MyDrive/Synthetic Stress Testin...,/content/drive/MyDrive/Synthetic Stress Testin...,180,180
1,test_hard_negative,synthetic_distractor_only,/content/drive/MyDrive/Synthetic Stress Testin...,/content/drive/MyDrive/Synthetic Stress Testin...,180,0
2,test_mixed,synthetic_drone_plus_distractor,/content/drive/MyDrive/Synthetic Stress Testin...,/content/drive/MyDrive/Synthetic Stress Testin...,180,180

Example generated config:
/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml
dataset:
  name: full_curated_v1
  root: data/evaluation/final_clean_full_curated_v1/test_drone_positive
  images_dir: data/evaluation/final_clean_full_curated_v1/test_drone_positive/images
  labels_dir: data/evaluation/final_clean_full_curated_v1/test_drone_positive/labels
  metadata_csv: data/evaluation/final_clean_full_curated_v1/test_drone_positive/metadata.csv
  image_width: 640
  image_height: 640
evaluation:
  iou_thresholds:
  - 0.25
  - 0.5
  confidence_thresholds:
  - 0.05
  - 0.1
  - 0.25
  - 0.5
  primary_iou_threshold: 0.5
  tiny_object_iou_threshold: 0.25
  target_class_name: drone
  drone_class_id: 0
  drone_like_classes:
  - drone
  - quadcopter
  - unmanned aerial vehicle
outputs:
  root: outputs/evaluation/final_clean_full_curated_v1/test_drone_positive
grounding_dino:
  repo_dir: external/GroundingDINO
  config_path: external/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
  checkpoint_path: weights/groundingdino/groundingdino_swint_ogc.pth
  device: cuda
  box_threshold: 0.2
  text_threshold: 0.2
  prompts:
  - drone
  - quadcopter
  - unmanned aerial vehicle
  - small drone in the sky
models:
- name: grounding_dino
  type: grounding_dino
  enabled: true
  weights: ''
  confidence: 0.05
  device: cuda
- name: yolo11n_drone_finetuned
  type: ultralytics_yolo
  enabled: true
  weights: outputs/training/yolo/yolo11n_drone_colab/weights/best.pt
  confidence: 0.05
  drone_like_classes:
  - drone
  drone_class_id: 0
- name: rtdetr_l_drone_finetuned
  type: ultralytics_rtdetr
  enabled: true
  weights: outputs/training/rtdetr/rtdetr_l_drone_colab/weights/best.pt
  confidence: 0.05
  drone_like_classes:
  - drone
  drone_class_id: 0

In [ ]:
#This will rebuild the local split folders properly:
from pathlib import Path
import shutil
import yaml
import pandas as pd

PROJECT_ROOT = Path("/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification")

DATASET_ROOT = PROJECT_ROOT / "data/synthetic/full_curated_v1"
DRIVE_SPLIT_ROOT = PROJECT_ROOT / "data/training/full_curated_v1_final_clean_split"
LOCAL_SPLIT_ROOT = Path("/content/drone_final_clean_training/full_curated_v1_final_clean_split")

SRC_IMAGES = DATASET_ROOT / "images"
SRC_LABELS = DATASET_ROOT / "labels"
SPLIT_METADATA = DRIVE_SPLIT_ROOT / "split_metadata.csv"

print("DATASET_ROOT exists:", DATASET_ROOT.exists())
print("SRC_IMAGES exists:", SRC_IMAGES.exists())
print("SRC_LABELS exists:", SRC_LABELS.exists())
print("SPLIT_METADATA exists:", SPLIT_METADATA.exists())

if not SPLIT_METADATA.exists():
    raise FileNotFoundError(f"Missing split metadata: {SPLIT_METADATA}")

df = pd.read_csv(SPLIT_METADATA)

print("\nColumns:", list(df.columns))
print(df.head())

# Detect the image id column
image_col_candidates = ["image_id", "filename", "image_name"]
image_col = next((c for c in image_col_candidates if c in df.columns), None)
if image_col is None:
    raise ValueError(f"Could not find image id column. Columns: {list(df.columns)}")

split_col = "split_final_clean"
if split_col not in df.columns:
    raise ValueError(f"Missing {split_col}. Columns: {list(df.columns)}")

print("\nUsing image column:", image_col)
print("Using split column:", split_col)

# Clean and rebuild only the local split folder
if LOCAL_SPLIT_ROOT.exists():
    print("\nRemoving broken local split:", LOCAL_SPLIT_ROOT)
    shutil.rmtree(LOCAL_SPLIT_ROOT)

for split in ["train", "val", "test"]:
    (LOCAL_SPLIT_ROOT / "images" / split).mkdir(parents=True, exist_ok=True)
    (LOCAL_SPLIT_ROOT / "labels" / split).mkdir(parents=True, exist_ok=True)

# Copy files into YOLO expected layout
counts = {"train": 0, "val": 0, "test": 0}
empty_labels = 0
missing_images = []

for _, row in df.iterrows():
    split = row[split_col]
    img_name = str(row[image_col])

    if split not in counts:
        continue

    src_img = SRC_IMAGES / img_name
    if not src_img.exists():
        missing_images.append(str(src_img))
        continue

    dst_img = LOCAL_SPLIT_ROOT / "images" / split / img_name
    shutil.copy2(src_img, dst_img)

    label_name = Path(img_name).with_suffix(".txt").name
    src_label = SRC_LABELS / label_name
    dst_label = LOCAL_SPLIT_ROOT / "labels" / split / label_name

    if src_label.exists():
        shutil.copy2(src_label, dst_label)
    else:
        dst_label.write_text("")
        empty_labels += 1

    counts[split] += 1

print("\nCopied counts:", counts)
print("Created empty labels:", empty_labels)
print("Missing images:", len(missing_images))
if missing_images[:5]:
    print("First missing images:", missing_images[:5])

if missing_images:
    raise FileNotFoundError("Some images were missing. Stop and inspect paths.")

# Write local train/val/test txt files
for split in ["train", "val", "test"]:
    image_paths = sorted((LOCAL_SPLIT_ROOT / "images" / split).glob("*.png"))
    txt_path = LOCAL_SPLIT_ROOT / f"{split}_images.txt"
    txt_path.write_text("\n".join(str(p) for p in image_paths) + "\n")
    print(f"{split}: wrote {len(image_paths)} paths to {txt_path}")

# Write local dataset.yaml
yaml_path = LOCAL_SPLIT_ROOT / "dataset.yaml"
data_yaml = {
    "path": str(LOCAL_SPLIT_ROOT),
    "train": str(LOCAL_SPLIT_ROOT / "train_images.txt"),
    "val": str(LOCAL_SPLIT_ROOT / "val_images.txt"),
    "test": str(LOCAL_SPLIT_ROOT / "test_images.txt"),
    "nc": 1,
    "names": {0: "drone"},
}

with open(yaml_path, "w") as f:
    yaml.safe_dump(data_yaml, f, sort_keys=False)

# Remove old Ultralytics cache files if any
for cache_file in LOCAL_SPLIT_ROOT.rglob("*.cache"):
    print("Removing cache:", cache_file)
    cache_file.unlink()

DATA_YAML = yaml_path

print("\n✅ Rebuilt local YOLO dataset correctly.")
print("DATA_YAML:", DATA_YAML)
print(yaml_path.read_text())

# Final verification
for split in ["train", "val", "test"]:
    n_img = len(list((LOCAL_SPLIT_ROOT / "images" / split).glob("*.png")))
    n_lab = len(list((LOCAL_SPLIT_ROOT / "labels" / split).glob("*.txt")))
    print(f"{split}: images={n_img}, labels={n_lab}")

    sample_img = next((LOCAL_SPLIT_ROOT / "images" / split).glob("*.png"), None)
    if sample_img:
        sample_label = LOCAL_SPLIT_ROOT / "labels" / split / sample_img.with_suffix(".txt").name
        print("  sample image exists:", sample_img.exists(), sample_img)
        print("  sample label exists:", sample_label.exists(), sample_label)

DATASET_ROOT exists: True
SRC_IMAGES exists: True
SRC_LABELS exists: True
SPLIT_METADATA exists: True

Columns: ['image_id', 'split', 'subset', 'target_present', 'target_class', 'distractor_classes', 'background_source', 'foreground_asset_source', 'background_type', 'background_path', 'background_filename', 'object_size_px', 'distance_bin', 'gaussian_noise_sigma', 'blur_level', 'contrast_level', 'lighting', 'difficulty', 'target_bbox', 'target_asset_id', 'distractor_bboxes', 'distractor_asset_ids', 'pasted_object_summary', 'bbox', 'asset_id', 'seed', 'foreground_asset_path', 'foreground_asset_id', 'foreground_source_dataset', 'generation_seed', 'background_id', 'background_category', 'drone_present', 'drone_asset_id', 'drone_bbox_x', 'drone_bbox_y', 'drone_bbox_w', 'drone_bbox_h', 'drone_size_px', 'distractor_present', 'distractor_type', 'distractor_asset_id', 'distractor_bbox_x', 'distractor_bbox_y', 'distractor_bbox_w', 'distractor_bbox_h', 'distractor_size_px', 'noise_sigma', 'blur_type', 'blur_strength', 'image_path', 'label_path', 'placement_mode', 'placement_region_x_min', 'placement_region_x_max', 'placement_region_y_min', 'placement_region_y_max', 'drone_center_x', 'drone_center_y', 'distractor_center_x', 'distractor_center_y', 'drone_distractor_iou', 'placement_attempts', 'split_final_clean']
         image_id            split                     subset  target_present  \
0  img_001334.png  full_curated_v1  synthetic_distractor_only           False
1  img_002505.png  full_curated_v1  synthetic_distractor_only           False
2  img_001497.png  full_curated_v1  synthetic_distractor_only           False
3  img_001295.png  full_curated_v1  synthetic_distractor_only           False
4  img_002386.png  full_curated_v1  synthetic_distractor_only           False

  target_class distractor_classes background_source foreground_asset_source  \
0         none           ["bird"]    manual_curated               processed
1         none           ["bird"]    manual_curated               processed
2         none       ["airplane"]    manual_curated               processed
3         none           ["bird"]    manual_curated               processed
4         none           ["bird"]    manual_curated               processed

              background_type  \
0                  cloudy_sky
1                  cloudy_sky
2             clear_upper_sky
3  sky_with_built_environment
4                  cloudy_sky

                                     background_path  ...  \
0  C:\Users\micha\Documents\studies\Masters\pract...  ...
1  C:\Users\micha\Documents\studies\Masters\pract...  ...
2  C:\Users\micha\Documents\studies\Masters\pract...  ...
3  C:\Users\micha\Documents\studies\Masters\pract...  ...
4  C:\Users\micha\Documents\studies\Masters\pract...  ...

  placement_region_x_max  placement_region_y_min placement_region_y_max  \
0                   0.95                    0.03                   0.55
1                   0.95                    0.03                   0.55
2                   0.95                    0.03                   0.55
3                   0.95                    0.03                   0.55
4                   0.95                    0.03                   0.55

   drone_center_x drone_center_y distractor_center_x distractor_center_y  \
0             NaN            NaN               494.0               209.0
1             NaN            NaN               116.0               320.0
2             NaN            NaN               221.5                27.5
3             NaN            NaN               195.0               278.0
4             NaN            NaN               284.0               138.0

  drone_distractor_iou placement_attempts split_final_clean
0                  NaN                  1             train
1                  NaN                  1             train
2                  NaN                  1             train
3                  NaN                  1             train
4                  NaN                  1             train

[5 rows x 64 columns]

Using image column: image_id
Using split column: split_final_clean

Removing broken local split: /content/drone_final_clean_training/full_curated_v1_final_clean_split

Copied counts: {'train': 2520, 'val': 540, 'test': 540}
Created empty labels: 0
Missing images: 0
train: wrote 2520 paths to /content/drone_final_clean_training/full_curated_v1_final_clean_split/train_images.txt
val: wrote 540 paths to /content/drone_final_clean_training/full_curated_v1_final_clean_split/val_images.txt
test: wrote 540 paths to /content/drone_final_clean_training/full_curated_v1_final_clean_split/test_images.txt

✅ Rebuilt local YOLO dataset correctly.
DATA_YAML: /content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml
path: /content/drone_final_clean_training/full_curated_v1_final_clean_split
train: /content/drone_final_clean_training/full_curated_v1_final_clean_split/train_images.txt
val: /content/drone_final_clean_training/full_curated_v1_final_clean_split/val_images.txt
test: /content/drone_final_clean_training/full_curated_v1_final_clean_split/test_images.txt
nc: 1
names:
  0: drone

train: images=2520, labels=2520
  sample image exists: True /content/drone_final_clean_training/full_curated_v1_final_clean_split/images/train/img_001380.png
  sample label exists: True /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train/img_001380.txt
val: images=540, labels=540
  sample image exists: True /content/drone_final_clean_training/full_curated_v1_final_clean_split/images/val/img_002730.png
  sample label exists: True /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/val/img_002730.txt
test: images=540, labels=540
  sample image exists: True /content/drone_final_clean_training/full_curated_v1_final_clean_split/images/test/img_001783.png
  sample label exists: True /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/test/img_001783.txt

In [ ]:
from pathlib import Path

expected = Path("/content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml")

print("DATA_YAML variable:", DATA_YAML)
print("Expected local path:", expected)
print("DATA_YAML exists:", Path(DATA_YAML).exists())
print("Is DATA_YAML local?", Path(DATA_YAML) == expected)

print("\nCurrent DATA_YAML contents:")
print(Path(DATA_YAML).read_text())

DATA_YAML variable: /content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml
Expected local path: /content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml
DATA_YAML exists: True
Is DATA_YAML local? True

Current DATA_YAML contents:
path: /content/drone_final_clean_training/full_curated_v1_final_clean_split
train: /content/drone_final_clean_training/full_curated_v1_final_clean_split/train_images.txt
val: /content/drone_final_clean_training/full_curated_v1_final_clean_split/val_images.txt
test: /content/drone_final_clean_training/full_curated_v1_final_clean_split/test_images.txt
nc: 1
names:
  0: drone

In [ ]:
# 8) Fine-tune YOLO11n
# Uses run_command(), which now streams logs live instead of buffering them until the end.
if RUN_YOLO_TRAINING:
    cmd = [
        sys.executable,
        "-u",
        "code/code/scripts/train/train_yolo.py",
        "--data", str(DATA_YAML),
        "--weights", "yolo11n.pt",
        "--epochs", str(EPOCHS_YOLO),
        "--imgsz", str(IMGSZ),
        "--batch", str(BATCH_YOLO),
        "--device", "0",
        "--name", YOLO_RUN_NAME,
        "--workers", "2",
    ]
    run_command(cmd)
else:
    print("Skipping YOLO training.")

Running:
/usr/bin/python3 -u scripts/train/train_yolo.py --data /content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml --weights yolo11n.pt --epochs 30 --imgsz 640 --batch 16 --device 0 --name yolo11n_drone_colab --workers 2

----- live output starts -----
Training YOLO from yolo11n.pt
  data=/content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml
  epochs=30 imgsz=640 batch=16 device=0
Ultralytics 8.4.80 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (NVIDIA A100-SXM4-80GB, 81153MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/drone_final_clean_training/full_curated_v1_final_clean_split/dataset.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dis=6.0, distill_model=None, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo11n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=yolo11n_drone_colab-9, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab-9, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    111296  ultralytics.nn.modules.block.C3k2            [384, 128, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     32096  ultralytics.nn.modules.block.C3k2            [256, 64, 1, False]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     86720  ultralytics.nn.modules.block.C3k2            [192, 128, 1, False]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    378880  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True]
 23        [16, 19, 22]  1    430867  ultralytics.nn.modules.head.Detect           [1, 16, None, [64, 128, 256]]
YOLO11n summary: 182 layers, 2,590,035 parameters, 2,590,019 gradients, 6.4 GFLOPs

Transferred 448/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2595.1±1481.7 MB/s, size: 840.1 KB)

train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 18 images, 6 backgrounds, 0 corrupt: 0% ──────────── 18/2520 52.8it/s 0.1s<47.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 45 images, 14 backgrounds, 0 corrupt: 1% ──────────── 45/2520 115.4it/s 0.2s<21.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 69 images, 20 backgrounds, 0 corrupt: 2% ──────────── 69/2520 152.7it/s 0.3s<16.0s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 98 images, 29 backgrounds, 0 corrupt: 3% ──────────── 98/2520 187.4it/s 0.4s<12.9s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 120 images, 35 backgrounds, 0 corrupt: 4% ╸─────────── 120/2520 196.3it/s 0.5s<12.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 142 images, 44 backgrounds, 0 corrupt: 5% ╸─────────── 142/2520 197.7it/s 0.6s<12.0s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 166 images, 49 backgrounds, 0 corrupt: 6% ╸─────────── 166/2520 203.1it/s 0.7s<11.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 194 images, 56 backgrounds, 0 corrupt: 7% ╸─────────── 194/2520 216.9it/s 0.8s<10.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 217 images, 63 backgrounds, 0 corrupt: 8% ━─────────── 217/2520 214.7it/s 1.0s<10.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 239 images, 69 backgrounds, 0 corrupt: 9% ━─────────── 239/2520 216.2it/s 1.1s<10.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 261 images, 74 backgrounds, 0 corrupt: 10% ━─────────── 261/2520 214.8it/s 1.2s<10.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 283 images, 82 backgrounds, 0 corrupt: 11% ━─────────── 283/2520 215.6it/s 1.3s<10.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 310 images, 94 backgrounds, 0 corrupt: 12% ━─────────── 310/2520 226.6it/s 1.4s<9.8s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 331 images, 96 backgrounds, 0 corrupt: 13% ━╸────────── 331/2520 221.2it/s 1.5s<9.9s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 357 images, 105 backgrounds, 0 corrupt: 14% ━╸────────── 357/2520 222.8it/s 1.6s<9.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 382 images, 118 backgrounds, 0 corrupt: 15% ━╸────────── 382/2520 228.1it/s 1.7s<9.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 405 images, 129 backgrounds, 0 corrupt: 16% ━╸────────── 405/2520 226.5it/s 1.8s<9.3s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 427 images, 138 backgrounds, 0 corrupt: 16% ━━────────── 427/2520 221.4it/s 1.9s<9.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 449 images, 144 backgrounds, 0 corrupt: 17% ━━────────── 449/2520 220.0it/s 2.0s<9.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 474 images, 151 backgrounds, 0 corrupt: 18% ━━────────── 474/2520 217.8it/s 2.1s<9.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 497 images, 161 backgrounds, 0 corrupt: 19% ━━────────── 497/2520 213.0it/s 2.2s<9.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 525 images, 169 backgrounds, 0 corrupt: 20% ━━────────── 525/2520 222.9it/s 2.3s<9.0s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 549 images, 175 backgrounds, 0 corrupt: 21% ━━╸───────── 549/2520 227.6it/s 2.4s<8.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 572 images, 184 backgrounds, 0 corrupt: 22% ━━╸───────── 572/2520 224.5it/s 2.6s<8.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 598 images, 194 backgrounds, 0 corrupt: 23% ━━╸───────── 598/2520 231.6it/s 2.7s<8.3s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 619 images, 200 backgrounds, 0 corrupt: 24% ━━╸───────── 619/2520 224.0it/s 2.8s<8.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 644 images, 210 backgrounds, 0 corrupt: 25% ━━━───────── 644/2520 230.1it/s 2.9s<8.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 667 images, 215 backgrounds, 0 corrupt: 26% ━━━───────── 667/2520 225.3it/s 3.0s<8.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 689 images, 219 backgrounds, 0 corrupt: 27% ━━━───────── 689/2520 223.0it/s 3.1s<8.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 711 images, 227 backgrounds, 0 corrupt: 28% ━━━───────── 711/2520 220.3it/s 3.2s<8.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 732 images, 236 backgrounds, 0 corrupt: 29% ━━━───────── 732/2520 213.4it/s 3.3s<8.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 757 images, 247 backgrounds, 0 corrupt: 30% ━━━╸──────── 757/2520 220.2it/s 3.4s<8.0s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 785 images, 255 backgrounds, 0 corrupt: 31% ━━━╸──────── 785/2520 233.1it/s 3.5s<7.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 806 images, 262 backgrounds, 0 corrupt: 31% ━━━╸──────── 806/2520 225.1it/s 3.6s<7.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 836 images, 276 backgrounds, 0 corrupt: 33% ━━━╸──────── 836/2520 241.5it/s 3.7s<7.0s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 858 images, 285 backgrounds, 0 corrupt: 34% ━━━━──────── 858/2520 233.8it/s 3.8s<7.1s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 883 images, 292 backgrounds, 0 corrupt: 35% ━━━━──────── 883/2520 234.1it/s 3.9s<7.0s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 906 images, 300 backgrounds, 0 corrupt: 35% ━━━━──────── 906/2520 224.0it/s 4.0s<7.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 936 images, 310 backgrounds, 0 corrupt: 37% ━━━━──────── 936/2520 233.0it/s 4.1s<6.8s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 964 images, 321 backgrounds, 0 corrupt: 38% ━━━━╸─────── 964/2520 239.2it/s 4.3s<6.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 987 images, 326 backgrounds, 0 corrupt: 39% ━━━━╸─────── 987/2520 234.9it/s 4.4s<6.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1012 images, 333 backgrounds, 0 corrupt: 40% ━━━━╸─────── 1012/2520 230.4it/s 4.5s<6.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1036 images, 340 backgrounds, 0 corrupt: 41% ━━━━╸─────── 1036/2520 226.9it/s 4.6s<6.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1057 images, 344 backgrounds, 0 corrupt: 41% ━━━━━─────── 1057/2520 219.5it/s 4.7s<6.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1080 images, 351 backgrounds, 0 corrupt: 42% ━━━━━─────── 1080/2520 220.9it/s 4.8s<6.5s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1103 images, 358 backgrounds, 0 corrupt: 43% ━━━━━─────── 1103/2520 216.3it/s 4.9s<6.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1128 images, 367 backgrounds, 0 corrupt: 44% ━━━━━─────── 1128/2520 225.7it/s 5.0s<6.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1154 images, 378 backgrounds, 0 corrupt: 45% ━━━━━─────── 1154/2520 233.7it/s 5.1s<5.8s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1180 images, 383 backgrounds, 0 corrupt: 46% ━━━━━╸────── 1180/2520 237.1it/s 5.2s<5.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1202 images, 391 backgrounds, 0 corrupt: 47% ━━━━━╸────── 1202/2520 229.3it/s 5.3s<5.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1227 images, 401 backgrounds, 0 corrupt: 48% ━━━━━╸────── 1227/2520 228.7it/s 5.4s<5.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1250 images, 411 backgrounds, 0 corrupt: 49% ━━━━━╸────── 1250/2520 223.0it/s 5.5s<5.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1271 images, 421 backgrounds, 0 corrupt: 50% ━━━━━━────── 1271/2520 212.8it/s 5.6s<5.9s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1293 images, 431 backgrounds, 0 corrupt: 51% ━━━━━━────── 1293/2520 214.1it/s 5.7s<5.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1316 images, 439 backgrounds, 0 corrupt: 52% ━━━━━━────── 1316/2520 210.4it/s 5.9s<5.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1340 images, 444 backgrounds, 0 corrupt: 53% ━━━━━━────── 1340/2520 208.9it/s 6.0s<5.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1364 images, 450 backgrounds, 0 corrupt: 54% ━━━━━━────── 1364/2520 217.0it/s 6.1s<5.3s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1387 images, 461 backgrounds, 0 corrupt: 55% ━━━━━━╸───── 1387/2520 215.0it/s 6.2s<5.3s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1413 images, 470 backgrounds, 0 corrupt: 56% ━━━━━━╸───── 1413/2520 217.2it/s 6.3s<5.1s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1436 images, 475 backgrounds, 0 corrupt: 56% ━━━━━━╸───── 1436/2520 207.6it/s 6.4s<5.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1459 images, 483 backgrounds, 0 corrupt: 57% ━━━━━━╸───── 1459/2520 207.5it/s 6.5s<5.1s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1486 images, 493 backgrounds, 0 corrupt: 58% ━━━━━━━───── 1486/2520 223.4it/s 6.6s<4.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1505 images, 504 backgrounds, 0 corrupt: 59% ━━━━━━━───── 1505/2520 211.1it/s 6.7s<4.8s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1529 images, 514 backgrounds, 0 corrupt: 60% ━━━━━━━───── 1529/2520 215.5it/s 6.8s<4.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1557 images, 520 backgrounds, 0 corrupt: 61% ━━━━━━━───── 1557/2520 233.5it/s 7.0s<4.1s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1578 images, 526 backgrounds, 0 corrupt: 62% ━━━━━━━╸──── 1578/2520 217.9it/s 7.1s<4.3s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1601 images, 534 backgrounds, 0 corrupt: 63% ━━━━━━━╸──── 1601/2520 216.4it/s 7.2s<4.2s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1628 images, 542 backgrounds, 0 corrupt: 64% ━━━━━━━╸──── 1628/2520 232.0it/s 7.3s<3.8s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1648 images, 548 backgrounds, 0 corrupt: 65% ━━━━━━━╸──── 1648/2520 220.0it/s 7.4s<4.0s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1671 images, 558 backgrounds, 0 corrupt: 66% ━━━━━━━╸──── 1671/2520 221.2it/s 7.5s<3.8s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1694 images, 570 backgrounds, 0 corrupt: 67% ━━━━━━━━──── 1694/2520 214.7it/s 7.6s<3.8s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1717 images, 579 backgrounds, 0 corrupt: 68% ━━━━━━━━──── 1717/2520 218.4it/s 7.7s<3.7s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1739 images, 587 backgrounds, 0 corrupt: 69% ━━━━━━━━──── 1739/2520 217.8it/s 7.8s<3.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1761 images, 597 backgrounds, 0 corrupt: 69% ━━━━━━━━──── 1761/2520 212.8it/s 7.9s<3.6s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1785 images, 605 backgrounds, 0 corrupt: 70% ━━━━━━━━──── 1785/2520 215.0it/s 8.0s<3.4s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1808 images, 613 backgrounds, 0 corrupt: 71% ━━━━━━━━╸─── 1808/2520 218.5it/s 8.1s<3.3s
train: Scanning /content/drone_final_clean_training/full_curated_v1_final_clean_split/labels/train... 1832 images, 618 backgrounds, 0 corrupt: 72% ━━━━━━━━╸─── 1832/2520 218.6it/s 8.2s<3.1s

In [ ]:
# 9) Inspect YOLO training results
import pandas as pd

yolo_root = PROJECT_ROOT / "outputs/training/yolo"
stable_yolo = yolo_root / YOLO_RUN_NAME
latest_yolo = get_latest_training_run(yolo_root, f"{YOLO_RUN_NAME}*")

print("Stable YOLO folder:", stable_yolo)
print("Latest YOLO folder:", latest_yolo)

for label, run_dir in [("stable", stable_yolo), ("latest", latest_yolo)]:
    if run_dir is None:
        continue
    weights_best = run_dir / "weights/best.pt"
    results_csv = run_dir / "results.csv"
    print(f"\n{label.upper()} YOLO best weights:", weights_best, "exists:", weights_best.exists())
    print(f"{label.upper()} YOLO results.csv:", results_csv, "exists:", results_csv.exists())
    if results_csv.exists():
        yolo_results = pd.read_csv(results_csv)
        print(f"{label.upper()} YOLO epochs:", len(yolo_results))
        display(yolo_results.tail())

Stable YOLO folder: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab
Latest YOLO folder: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab-9

STABLE YOLO best weights: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab/weights/best.pt exists: True
STABLE YOLO results.csv: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab/results.csv exists: True
STABLE YOLO epochs: 30

,epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
25,26,390.302,1.87272,1.60086,1.25133,0.50000,0.56552,0.49535,0.20935,1.91642,1.58180,1.30507,0.000350,0.000350,0.000350
26,27,403.436,1.85931,1.63125,1.23196,0.47561,0.55045,0.50841,0.22807,1.87148,1.55491,1.27199,0.000284,0.000284,0.000284
27,28,416.729,1.84009,1.63754,1.22470,0.51329,0.53821,0.51853,0.23432,1.83300,1.50185,1.25394,0.000218,0.000218,0.000218
28,29,429.837,1.81727,1.59613,1.23711,0.53052,0.57241,0.55470,0.24955,1.82812,1.55066,1.24967,0.000152,0.000152,0.000152
29,30,443.319,1.79738,1.55943,1.22804,0.51046,0.55374,0.53555,0.24151,1.83378,1.52233,1.24812,0.000086,0.000086,0.000086

LATEST YOLO best weights: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab-9/weights/best.pt exists: True
LATEST YOLO results.csv: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab-9/results.csv exists: True
LATEST YOLO epochs: 30

,epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
25,26,781.510,1.80355,1.51911,1.18941,0.66139,0.47222,0.49310,0.22711,1.84018,1.52453,1.20167,0.000350,0.000350,0.000350
26,27,809.200,1.82862,1.54068,1.19615,0.69699,0.46667,0.51178,0.24265,1.83509,1.46287,1.20429,0.000284,0.000284,0.000284
27,28,836.500,1.80620,1.56530,1.18937,0.70929,0.48611,0.52606,0.24082,1.79449,1.48883,1.18187,0.000218,0.000218,0.000218
28,29,863.721,1.78337,1.50190,1.19581,0.67149,0.53611,0.54813,0.26427,1.76836,1.43764,1.17300,0.000152,0.000152,0.000152
29,30,891.019,1.80514,1.50904,1.19259,0.65779,0.50278,0.53727,0.26214,1.73799,1.43258,1.16260,0.000086,0.000086,0.000086

In [ ]:
# 10) Fine-tune RT-DETR-L
# RT-DETR is heavier than YOLO. This cell now streams progress live.
# Safety guard in Cell 1 prevents accidentally running RT-DETR-L on slow GPUs like T4.
if RUN_RTDETR_TRAINING:
    cmd = [
        sys.executable,
        "-u",
        "code/code/scripts/train/train_rtdetr.py",
        "--data", str(DATA_YAML),
        "--weights", "rtdetr-l.pt",
        "--epochs", str(EPOCHS_RTDETR),
        "--imgsz", str(IMGSZ),
        "--batch", str(BATCH_RTDETR),
        "--device", "0",
        "--name", RTDETR_RUN_NAME,
        "--workers", "2",
    ]
    run_command(cmd)
else:
    print("Skipping RT-DETR training.")

Streaming output truncated to the last 5000 lines.
        2/5      5.71G      1.185     0.4961     0.1642          3       1280: 33% ━━━━──────── 424/1260 3.5it/s 2:05<4:02
        2/5      5.71G      1.184     0.4965      0.164          6       1280: 33% ━━━━──────── 425/1260 3.5it/s 2:05<4:01
        2/5      5.71G      1.183     0.4965      0.164          1       1280: 33% ━━━━──────── 426/1260 3.5it/s 2:05<3:60
        2/5      5.71G      1.183     0.4961     0.1642          7       1280: 33% ━━━━──────── 427/1260 3.5it/s 2:06<4:01
        2/5      5.71G      1.183     0.4959      0.164          4       1280: 33% ━━━━──────── 428/1260 3.5it/s 2:06<4:00
        2/5      5.71G      1.187     0.4957     0.1653          4       1280: 34% ━━━━──────── 429/1260 3.5it/s 2:06<3:60
        2/5      5.71G      1.186     0.4957     0.1651          6       1280: 34% ━━━━──────── 430/1260 3.3it/s 2:07<4:12
        2/5      5.71G      1.186     0.4957     0.1652          6       1280: 34% ━━━━──────── 431/1260 3.4it/s 2:07<4:05
        2/5      5.71G      1.185     0.4955      0.165          4       1280: 34% ━━━━──────── 432/1260 3.4it/s 2:07<4:04
        2/5      5.71G      1.185      0.495     0.1655          2       1280: 34% ━━━━──────── 433/1260 3.4it/s 2:07<4:01
        2/5      5.71G      1.188     0.4944     0.1661          5       1280: 34% ━━━━──────── 434/1260 3.4it/s 2:08<4:00
        2/5      5.71G      1.187     0.4947     0.1658          3       1280: 34% ━━━━──────── 435/1260 3.4it/s 2:08<4:01
        2/5      5.71G      1.186     0.4946     0.1655          3       1280: 34% ━━━━──────── 436/1260 3.4it/s 2:08<3:60
        2/5      5.71G      1.187     0.4946     0.1655          4       1280: 34% ━━━━──────── 437/1260 3.4it/s 2:09<3:60
        2/5      5.71G      1.188     0.4941     0.1655          4       1280: 34% ━━━━──────── 438/1260 3.4it/s 2:09<3:58
        2/5      5.71G      1.189     0.4938     0.1655          4       1280: 34% ━━━━──────── 439/1260 3.5it/s 2:09<3:57
        2/5      5.71G      1.189     0.4937     0.1653          2       1280: 34% ━━━━──────── 440/1260 3.5it/s 2:09<3:57
        2/5      5.71G      1.189     0.4935     0.1651          2       1280: 35% ━━━━──────── 441/1260 3.5it/s 2:10<3:57
        2/5      5.71G      1.188      0.494     0.1649          5       1280: 35% ━━━━──────── 442/1260 3.5it/s 2:10<3:56
        2/5      5.71G      1.187     0.4938     0.1648          5       1280: 35% ━━━━──────── 443/1260 3.5it/s 2:10<3:55
        2/5      5.71G       1.19      0.493     0.1653          4       1280: 35% ━━━━──────── 444/1260 3.5it/s 2:11<3:54
        2/5      5.71G      1.189     0.4927     0.1651          5       1280: 35% ━━━━──────── 445/1260 3.3it/s 2:11<4:06
        2/5      5.71G      1.192     0.4918     0.1657          3       1280: 35% ━━━━──────── 446/1260 3.4it/s 2:11<4:00
        2/5      5.71G      1.194      0.491     0.1664          5       1280: 35% ━━━━──────── 447/1260 3.4it/s 2:12<3:59
        2/5      5.71G      1.193     0.4917     0.1661          2       1280: 35% ━━━━──────── 448/1260 3.4it/s 2:12<3:58
        2/5      5.71G      1.195     0.4915     0.1672          4       1280: 35% ━━━━──────── 449/1260 3.4it/s 2:12<3:57
        2/5      5.71G      1.197     0.4909     0.1673          3       1280: 35% ━━━━──────── 450/1260 3.4it/s 2:12<3:56
        2/5      5.71G      1.198     0.4905     0.1678          4       1280: 35% ━━━━──────── 451/1260 3.4it/s 2:13<3:56
        2/5      5.71G      1.197     0.4904     0.1675          3       1280: 35% ━━━━──────── 452/1260 3.4it/s 2:13<3:56
        2/5      5.71G      1.196     0.4907     0.1673          4       1280: 35% ━━━━──────── 453/1260 3.4it/s 2:13<3:54
        2/5      5.71G      1.195     0.4909     0.1671          6       1280: 36% ━━━━──────── 454/1260 3.4it/s 2:14<3:54
        2/5      5.71G      1.196     0.4902     0.1676          6       1280: 36% ━━━━──────── 455/1260 3.4it/s 2:14<3:56
        2/5      5.71G      1.199     0.4896     0.1682          6       1280: 36% ━━━━──────── 456/1260 3.4it/s 2:14<3:58
        2/5      5.71G      1.199     0.4892     0.1687          5       1280: 36% ━━━━──────── 457/1260 3.4it/s 2:14<3:57
        2/5      5.71G      1.199      0.489     0.1689          3       1280: 36% ━━━━──────── 458/1260 3.4it/s 2:15<3:56
        2/5      5.71G      1.197      0.489     0.1686          0       1280: 36% ━━━━──────── 459/1260 3.8it/s 2:15<3:31
        2/5      5.71G      1.195     0.4891     0.1683          4       1280: 36% ━━━━──────── 460/1260 3.5it/s 2:15<3:46
        2/5      5.71G      1.194     0.4888     0.1683          7       1280: 36% ━━━━──────── 461/1260 3.5it/s 2:16<3:45
        2/5      5.71G      1.195     0.4886     0.1687          3       1280: 36% ━━━━──────── 462/1260 3.5it/s 2:16<3:46
        2/5      5.71G      1.196     0.4883     0.1692          6       1280: 36% ━━━━──────── 463/1260 3.5it/s 2:16<3:46
        2/5      5.71G      1.195     0.4887     0.1692          5       1280: 36% ━━━━──────── 464/1260 3.5it/s 2:16<3:46
        2/5      5.71G      1.196     0.4884     0.1691          3       1280: 36% ━━━━──────── 465/1260 3.5it/s 2:17<3:47
        2/5      5.71G      1.196     0.4886     0.1693          4       1280: 36% ━━━━──────── 466/1260 3.5it/s 2:17<3:47
        2/5      5.71G      1.196     0.4883     0.1694          6       1280: 37% ━━━━──────── 467/1260 3.5it/s 2:17<3:48
        2/5      5.71G      1.195     0.4892     0.1691          5       1280: 37% ━━━━──────── 468/1260 3.5it/s 2:18<3:48
        2/5      5.71G      1.194     0.4895     0.1688          2       1280: 37% ━━━━──────── 469/1260 3.5it/s 2:18<3:49
        2/5      5.71G      1.192     0.4904     0.1685          1       1280: 37% ━━━━──────── 470/1260 3.5it/s 2:18<3:48
        2/5      5.71G      1.191     0.4913     0.1683          1       1280: 37% ━━━━──────── 471/1260 3.5it/s 2:18<3:48
        2/5      5.71G      1.191     0.4909     0.1686          3       1280: 37% ━━━━──────── 472/1260 3.4it/s 2:19<3:49
        2/5      5.71G      1.192     0.4907     0.1687          3       1280: 37% ━━━━╸─────── 473/1260 3.4it/s 2:19<3:49
        2/5      5.71G      1.194     0.4902     0.1689          6       1280: 37% ━━━━╸─────── 474/1260 3.4it/s 2:19<3:53
        2/5      5.71G      1.196     0.4896     0.1693          2       1280: 37% ━━━━╸─────── 475/1260 3.2it/s 2:20<4:02
        2/5      5.71G      1.195       0.49      0.169          3       1280: 37% ━━━━╸─────── 476/1260 3.3it/s 2:20<3:57
        2/5      5.71G      1.195     0.4897     0.1688          2       1280: 37% ━━━━╸─────── 477/1260 3.4it/s 2:20<3:54
        2/5      5.71G      1.197      0.489       0.17          4       1280: 37% ━━━━╸─────── 478/1260 3.4it/s 2:21<3:51
        2/5      5.71G        1.2     0.4883     0.1708          3       1280: 38% ━━━━╸─────── 479/1260 3.4it/s 2:21<3:49
        2/5      5.71G      1.201     0.4877     0.1713          4       1280: 38% ━━━━╸─────── 480/1260 3.4it/s 2:21<3:49
        2/5      5.71G      1.201     0.4878     0.1713          5       1280: 38% ━━━━╸─────── 481/1260 3.4it/s 2:21<3:47
        2/5      5.71G      1.201     0.4878     0.1713          6       1280: 38% ━━━━╸─────── 482/1260 3.4it/s 2:22<3:46
        2/5      5.71G      1.202     0.4876     0.1717          7       1280: 38% ━━━━╸─────── 483/1260 3.4it/s 2:22<3:45
        2/5      5.71G      1.201     0.4879     0.1714          1       1280: 38% ━━━━╸─────── 484/1260 3.5it/s 2:22<3:44
        2/5      5.71G        1.2      0.489     0.1711          2       1280: 38% ━━━━╸─────── 485/1260 3.5it/s 2:23<3:43
        2/5      5.71G      1.198     0.4895     0.1708          4       1280: 38% ━━━━╸─────── 486/1260 3.5it/s 2:23<3:43
        2/5      5.71G      1.198     0.4895     0.1706          4       1280: 38% ━━━━╸─────── 487/1260 3.5it/s 2:23<3:43
        2/5      5.71G      1.197     0.4894     0.1704          4       1280: 38% ━━━━╸─────── 488/1260 3.5it/s 2:23<3:42
        2/5      5.71G      1.195     0.4899     0.1701          1       1280: 38% ━━━━╸─────── 489/1260 3.5it/s 2:24<3:42
        2/5      5.71G      1.195     0.4898     0.1703          3       1280: 38% ━━━━╸─────── 490/1260 3.3it/s 2:24<3:53
        2/5      5.71G      1.195     0.4902     0.1708          5       1280: 38% ━━━━╸─────── 491/1260 3.3it/s 2:24<3:51
        2/5      5.71G      1.195     0.4906     0.1706          1       1280: 39% ━━━━╸─────── 492/1260 3.4it/s 2:25<3:49
        2/5      5.71G      1.196     0.4901     0.1711          6       1280: 39% ━━━━╸─────── 493/1260 3.4it/s 2:25<3:47
        2/5      5.71G      1.196       0.49     0.1712          3       1280: 39% ━━━━╸─────── 494/1260 3.4it/s 2:25<3:47
        2/5      5.71G      1.196     0.4902     0.1711          7       1280: 39% ━━━━╸─────── 495/1260 3.3it/s 2:26<3:49
        2/5      5.71G      1.195     0.4907     0.1708          4       1280: 39% ━━━━╸─────── 496/1260 3.4it/s 2:26<3:48
        2/5      5.71G      1.195     0.4909     0.1713          4       1280: 39% ━━━━╸─────── 497/1260 3.4it/s 2:26<3:47
        2/5      5.71G      1.195     0.4909     0.1713          6       1280: 39% ━━━━╸─────── 498/1260 3.4it/s 2:26<3:46
        2/5      5.71G      1.195      0.491     0.1712          5       1280: 39% ━━━━╸─────── 499/1260 3.4it/s 2:27<3:45
        2/5      5.71G      1.194     0.4913     0.1712          3       1280: 39% ━━━━╸─────── 500/1260 3.4it/s 2:27<3:44
        2/5      5.71G      1.195     0.4908     0.1716          4       1280: 39% ━━━━╸─────── 501/1260 3.4it/s 2:27<3:41
        2/5      5.71G        1.2     0.4901     0.1737          1       1280: 39% ━━━━╸─────── 502/1260 3.5it/s 2:28<3:39
        2/5      5.71G      1.199     0.4907     0.1735          2       1280: 39% ━━━━╸─────── 503/1260 3.5it/s 2:28<3:38
        2/5      5.71G      1.198     0.4908     0.1732          5       1280: 40% ━━━━╸─────── 504/1260 3.5it/s 2:28<3:38
        2/5      5.71G      1.198     0.4905     0.1732          3       1280: 40% ━━━━╸─────── 505/1260 3.3it/s 2:29<3:49
        2/5      5.71G        1.2       0.49     0.1749          3       1280: 40% ━━━━╸─────── 506/1260 3.4it/s 2:29<3:43
        2/5      5.71G      1.203     0.4896     0.1754          3       1280: 40% ━━━━╸─────── 507/1260 3.4it/s 2:29<3:41
        2/5      5.71G      1.204     0.4892      0.176          5       1280: 40% ━━━━╸─────── 508/1260 3.4it/s 2:29<3:39
        2/5      5.71G      1.205     0.4894     0.1762          5       1280: 40% ━━━━╸─────── 509/1260 3.4it/s 2:30<3:38
        2/5      5.71G      1.206     0.4885     0.1771          4       1280: 40% ━━━━╸─────── 510/1260 3.5it/s 2:30<3:36
        2/5      5.71G      1.206     0.4887     0.1768          2       1280: 40% ━━━━╸─────── 511/1260 3.5it/s 2:30<3:37
        2/5      5.71G      1.205     0.4889     0.1766          3       1280: 40% ━━━━╸─────── 512/1260 3.5it/s 2:31<3:37
        2/5      5.71G      1.204      0.489     0.1763          4       1280: 40% ━━━━╸─────── 513/1260 3.5it/s 2:31<3:36
        2/5      5.71G      1.207     0.4881      0.177          5       1280: 40% ━━━━╸─────── 514/1260 3.4it/s 2:31<3:38
        2/5      5.71G      1.208      0.488     0.1776          4       1280: 40% ━━━━╸─────── 515/1260 3.4it/s 2:31<3:37
        2/5      5.71G      1.211     0.4878      0.178          2       1280: 40% ━━━━╸─────── 516/1260 3.5it/s 2:32<3:36
        2/5      5.71G       1.21      0.488      0.178          6       1280: 41% ━━━━╸─────── 517/1260 3.5it/s 2:32<3:35
        2/5      5.71G      1.211     0.4878      0.178          3       1280: 41% ━━━━╸─────── 518/1260 3.5it/s 2:32<3:35
        2/5      5.71G       1.21     0.4883     0.1778          5       1280: 41% ━━━━╸─────── 519/1260 3.5it/s 2:33<3:34
        2/5      5.71G       1.21     0.4885     0.1777          4       1280: 41% ━━━━╸─────── 520/1260 3.5it/s 2:33<3:33
        2/5      5.71G       1.21     0.4883     0.1778          5       1280: 41% ━━━━╸─────── 521/1260 3.3it/s 2:33<3:43
        2/5      5.71G      1.211     0.4884     0.1778          3       1280: 41% ━━━━╸─────── 522/1260 3.4it/s 2:33<3:38
        2/5      5.71G       1.21     0.4887     0.1775          5       1280: 41% ━━━━╸─────── 523/1260 3.4it/s 2:34<3:35
        2/5      5.71G      1.211     0.4882     0.1775          3       1280: 41% ━━━━╸─────── 524/1260 3.4it/s 2:34<3:37
        2/5      5.71G      1.208     0.4879     0.1771          0       1280: 41% ━━━━━─────── 525/1260 3.9it/s 2:34<3:11
        2/5      5.71G       1.21     0.4878     0.1775          6       1280: 41% ━━━━━─────── 526/1260 3.8it/s 2:35<3:16
        2/5      5.71G      1.208     0.4881     0.1772          3       1280: 41% ━━━━━─────── 527/1260 3.7it/s 2:35<3:19
        2/5      5.71G      1.209     0.4878     0.1774          4       1280: 41% ━━━━━─────── 528/1260 3.6it/s 2:35<3:22
        2/5      5.71G      1.208     0.4882     0.1772          5       1280: 41% ━━━━━─────── 529/1260 3.6it/s 2:35<3:24
        2/5      5.71G      1.209     0.4879     0.1774          7       1280: 42% ━━━━━─────── 530/1260 3.6it/s 2:36<3:24
        2/5      5.71G      1.208      0.488     0.1773          1       1280: 42% ━━━━━─────── 531/1260 3.5it/s 2:36<3:29
        2/5      5.71G      1.208     0.4877     0.1774          3       1280: 42% ━━━━━─────── 532/1260 3.5it/s 2:36<3:28
        2/5      5.71G      1.207     0.4881     0.1772          1       1280: 42% ━━━━━─────── 533/1260 3.5it/s 2:37<3:27
        2/5      5.71G      1.207     0.4882     0.1779          4       1280: 42% ━━━━━─────── 534/1260 3.5it/s 2:37<3:27
        2/5      5.71G      1.206     0.4881     0.1778          5       1280: 42% ━━━━━─────── 535/1260 3.5it/s 2:37<3:28
        2/5      5.71G      1.205     0.4885     0.1776          1       1280: 42% ━━━━━─────── 536/1260 3.5it/s 2:37<3:27
        2/5      5.71G      1.209     0.4879     0.1794          1       1280: 42% ━━━━━─────── 537/1260 3.3it/s 2:38<3:37
        2/5      5.71G      1.211      0.488     0.1801          4       1280: 42% ━━━━━─────── 538/1260 3.4it/s 2:38<3:35
        2/5      5.71G      1.213     0.4874     0.1811          2       1280: 42% ━━━━━─────── 539/1260 3.4it/s 2:38<3:33
        2/5      5.71G      1.212     0.4883     0.1808          3       1280: 42% ━━━━━─────── 540/1260 3.4it/s 2:39<3:31
        2/5      5.71G      1.213      0.488     0.1815          2       1280: 42% ━━━━━─────── 541/1260 3.4it/s 2:39<3:32
        2/5      5.71G      1.216     0.4872      0.182          2       1280: 43% ━━━━━─────── 542/1260 3.4it/s 2:39<3:33
        2/5      5.71G      1.218     0.4867     0.1825          5       1280: 43% ━━━━━─────── 543/1260 3.4it/s 2:40<3:33
        2/5      5.71G      1.218     0.4869     0.1826          5       1280: 43% ━━━━━─────── 544/1260 3.4it/s 2:40<3:30
        2/5      5.71G      1.218     0.4869     0.1825          7       1280: 43% ━━━━━─────── 545/1260 3.4it/s 2:40<3:29
        2/5      5.71G      1.217     0.4873     0.1822          2       1280: 43% ━━━━━─────── 546/1260 3.4it/s 2:40<3:28
        2/5      5.71G      1.217     0.4878      0.182          1       1280: 43% ━━━━━─────── 547/1260 3.4it/s 2:41<3:27
        2/5      5.71G      1.218     0.4877     0.1823          6       1280: 43% ━━━━━─────── 548/1260 3.5it/s 2:41<3:25
        2/5      5.71G       1.22     0.4874     0.1829          2       1280: 43% ━━━━━─────── 549/1260 3.5it/s 2:41<3:25
        2/5      5.71G      1.219     0.4877     0.1827          5       1280: 43% ━━━━━─────── 550/1260 3.5it/s 2:42<3:24
        2/5      5.71G      1.219     0.4876     0.1827          5       1280: 43% ━━━━━─────── 551/1260 3.5it/s 2:42<3:24
        2/5      5.71G       1.22     0.4875     0.1829          5       1280: 43% ━━━━━─────── 552/1260 3.5it/s 2:42<3:23
        2/5      5.71G      1.219     0.4876     0.1826          1       1280: 43% ━━━━━─────── 553/1260 3.3it/s 2:42<3:34
        2/5      5.71G      1.222      0.487      0.184          4       1280: 43% ━━━━━─────── 554/1260 3.4it/s 2:43<3:30
        2/5      5.71G      1.222     0.4867     0.1839          4       1280: 44% ━━━━━─────── 555/1260 3.4it/s 2:43<3:28
        2/5      5.71G      1.223     0.4865     0.1839          4       1280: 44% ━━━━━─────── 556/1260 3.4it/s 2:43<3:26
        2/5      5.71G      1.221     0.4866     0.1836          3       1280: 44% ━━━━━─────── 557/1260 3.4it/s 2:44<3:25
        2/5      5.71G      1.222     0.4868     0.1836          4       1280: 44% ━━━━━─────── 558/1260 3.5it/s 2:44<3:23
        2/5      5.71G      1.221     0.4867     0.1834          3       1280: 44% ━━━━━─────── 559/1260 3.5it/s 2:44<3:22
        2/5      5.71G      1.225     0.4859     0.1837          3       1280: 44% ━━━━━─────── 560/1260 3.5it/s 2:44<3:21
        2/5      5.71G      1.228     0.4851     0.1845          3       1280: 44% ━━━━━─────── 561/1260 3.5it/s 2:45<3:21
        2/5      5.71G      1.228     0.4851     0.1845          5       1280: 44% ━━━━━─────── 562/1260 3.5it/s 2:45<3:20
        2/5      5.71G      1.227     0.4853     0.1843          2       1280: 44% ━━━━━─────── 563/1260 3.5it/s 2:45<3:20
        2/5      5.71G      1.227     0.4854     0.1843          4       1280: 44% ━━━━━─────── 564/1260 3.5it/s 2:46<3:20
        2/5      5.71G      1.226     0.4854      0.184          5       1280: 44% ━━━━━─────── 565/1260 3.5it/s 2:46<3:19
        2/5      5.71G      1.225     0.4859     0.1838          4       1280: 44% ━━━━━─────── 566/1260 3.5it/s 2:46<3:19
        2/5      5.71G      1.225     0.4861     0.1836          4       1280: 45% ━━━━━─────── 567/1260 3.5it/s 2:46<3:19
        2/5      5.71G      1.226      0.486      0.184          5       1280: 45% ━━━━━─────── 568/1260 3.5it/s 2:47<3:20
        2/5      5.71G       1.23     0.4853     0.1844          2       1280: 45% ━━━━━─────── 569/1260 3.3it/s 2:47<3:29
        2/5      5.71G       1.23     0.4852      0.185          3       1280: 45% ━━━━━─────── 570/1260 3.4it/s 2:47<3:25
        2/5      5.71G      1.232     0.4847     0.1851          4       1280: 45% ━━━━━─────── 571/1260 3.4it/s 2:48<3:22
        2/5      5.71G      1.233     0.4843     0.1858          4       1280: 45% ━━━━━─────── 572/1260 3.4it/s 2:48<3:21
        2/5      5.71G      1.233     0.4843     0.1857          4       1280: 45% ━━━━━─────── 573/1260 3.4it/s 2:48<3:19
        2/5      5.71G      1.232     0.4844     0.1854          2       1280: 45% ━━━━━─────── 574/1260 3.4it/s 2:49<3:19
        2/5      5.71G      1.233     0.4842     0.1853          3       1280: 45% ━━━━━─────── 575/1260 3.4it/s 2:49<3:19
        2/5      5.71G      1.233     0.4842     0.1856          6       1280: 45% ━━━━━─────── 576/1260 3.4it/s 2:49<3:19
        2/5      5.71G      1.236     0.4836     0.1863          7       1280: 45% ━━━━━─────── 577/1260 3.5it/s 2:49<3:18
        2/5      5.71G      1.236     0.4834     0.1863          4       1280: 45% ━━━━━╸────── 578/1260 3.4it/s 2:50<3:18
        2/5      5.71G      1.235     0.4835      0.186          2       1280: 45% ━━━━━╸────── 579/1260 3.4it/s 2:50<3:18
        2/5      5.71G      1.234     0.4836     0.1858          6       1280: 46% ━━━━━╸────── 580/1260 3.4it/s 2:50<3:17
        2/5      5.71G      1.233     0.4846     0.1856          2       1280: 46% ━━━━━╸────── 581/1260 3.5it/s 2:51<3:17
        2/5      5.71G      1.232     0.4848     0.1853          1       1280: 46% ━━━━━╸────── 582/1260 3.5it/s 2:51<3:16
        2/5      5.71G      1.232     0.4846     0.1852          1       1280: 46% ━━━━━╸────── 583/1260 3.5it/s 2:51<3:15
        2/5      5.71G      1.232     0.4846      0.185          3       1280: 46% ━━━━━╸────── 584/1260 3.5it/s 2:51<3:15
        2/5      5.71G      1.231     0.4848     0.1848          1       1280: 46% ━━━━━╸────── 585/1260 3.3it/s 2:52<3:25

In [ ]:
# 11) Sync latest Ultralytics runs to stable folders expected by eval config
# This fixes the common Colab/Ultralytics issue where new training runs are saved as -2, -3, ...
# while the eval config still points to the original stable folder name.

if RUN_YOLO_TRAINING or RUN_YOLO_INFERENCE:
    sync_latest_run_to_stable(
        PROJECT_ROOT / "outputs/training/yolo",
        f"{YOLO_RUN_NAME}*",
        YOLO_RUN_NAME,
    )

if RUN_RTDETR_TRAINING or RUN_RTDETR_INFERENCE:
    sync_latest_run_to_stable(
        PROJECT_ROOT / "outputs/training/rtdetr",
        f"{RTDETR_RUN_NAME}*",
        RTDETR_RUN_NAME,
    )

# Show final stable folders and epoch counts
for label, root, run_name in [
    ("YOLO", PROJECT_ROOT / "outputs/training/yolo", YOLO_RUN_NAME),
    ("RT-DETR", PROJECT_ROOT / "outputs/training/rtdetr", RTDETR_RUN_NAME),
]:
    stable = root / run_name
    results_csv = stable / "results.csv"
    weights = stable / "weights/best.pt"
    print(f"\n{label} stable folder: {stable}")
    print("  weights exists:", weights.exists())
    print("  results exists:", results_csv.exists())
    if results_csv.exists():
        df = pd.read_csv(results_csv)
        print("  epochs:", len(df))
        display(df.tail())

Stable folder is already latest: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab
Stable folder is already latest: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/rtdetr/rtdetr_l_drone_colab

YOLO stable folder: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab
  weights exists: True
  results exists: True
  epochs: 30

,epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
25,26,781.510,1.80355,1.51911,1.18941,0.66139,0.47222,0.49310,0.22711,1.84018,1.52453,1.20167,0.000350,0.000350,0.000350
26,27,809.200,1.82862,1.54068,1.19615,0.69699,0.46667,0.51178,0.24265,1.83509,1.46287,1.20429,0.000284,0.000284,0.000284
27,28,836.500,1.80620,1.56530,1.18937,0.70929,0.48611,0.52606,0.24082,1.79449,1.48883,1.18187,0.000218,0.000218,0.000218
28,29,863.721,1.78337,1.50190,1.19581,0.67149,0.53611,0.54813,0.26427,1.76836,1.43764,1.17300,0.000152,0.000152,0.000152
29,30,891.019,1.80514,1.50904,1.19259,0.65779,0.50278,0.53727,0.26214,1.73799,1.43258,1.16260,0.000086,0.000086,0.000086

RT-DETR stable folder: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/rtdetr/rtdetr_l_drone_colab
  weights exists: True
  results exists: True
  epochs: 5

,epoch,time,train/giou_loss,train/cls_loss,train/l1_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/giou_loss,val/cls_loss,val/l1_loss,lr/pg0,lr/pg1,lr/pg2
0,1,395.892,1.68418,0.87376,0.38718,0.55050,0.36389,0.36501,0.11946,1.43877,0.43559,0.32136,0.000666,0.000666,0.000666
1,2,776.801,1.25774,0.49599,0.18342,0.62179,0.38333,0.40676,0.16939,1.13768,0.65327,0.19323,0.001069,0.001069,0.001069
2,3,1157.100,1.23123,0.47816,0.17890,0.50781,0.33333,0.32152,0.09621,NaN,NaN,NaN,0.001208,0.001208,0.001208
3,4,1537.110,1.26169,0.53930,0.19253,0.40188,0.33611,0.28951,0.11797,NaN,NaN,NaN,0.000812,0.000812,0.000812
4,5,1918.650,1.19350,0.50593,0.17406,0.55561,0.44453,0.42175,0.17061,NaN,NaN,NaN,0.000416,0.000416,0.000416

In [ ]:
# 12) Inference on each held-out evaluation subset
# Runs each enabled detector on:
# - test_drone_positive
# - test_hard_negative
# - test_mixed

models_to_run = []
if RUN_GDINO:
    models_to_run.append("grounding_dino")
if RUN_YOLO_INFERENCE:
    models_to_run.append("yolo11n_drone_finetuned")
if RUN_RTDETR_INFERENCE:
    models_to_run.append("rtdetr_l_drone_finetuned")

for eval_name, job in EVAL_JOBS.items():
    print("\n" + "#" * 100)
    print("EVAL SUBSET:", eval_name, "| source subset:", job["subset"], "| images:", job["n_images"])
    print("#" * 100)

    # Delete stale predictions for this eval subset.
    pred_dir = job["output_root"] / "predictions"
    pred_dir.mkdir(parents=True, exist_ok=True)
    if RESET_PREDICTIONS:
        for model_name in models_to_run:
            p = pred_dir / f"{model_name}_predictions.csv"
            if p.exists():
                p.unlink()
                print("Deleted stale prediction file:", p)

    base_cmd = [
        sys.executable,
        "code/code/scripts/eval/run_detectors.py",
        "--config", str(job["config"]),
        "--project-root", str(PROJECT_ROOT),
    ]

    if RUN_GDINO:
        run_command(base_cmd + ["--models", "grounding_dino"], check=True)

    if RUN_YOLO_INFERENCE:
        run_command(base_cmd + ["--models", "yolo11n_drone_finetuned"], check=False)

    if RUN_RTDETR_INFERENCE:
        run_command(base_cmd + ["--models", "rtdetr_l_drone_finetuned"], check=False)

####################################################################################################
EVAL SUBSET: test_drone_positive | source subset: synthetic_drone_positive | images: 180
####################################################################################################
Deleted stale prediction file: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/grounding_dino_predictions.csv
Deleted stale prediction file: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/yolo11n_drone_finetuned_predictions.csv
Deleted stale prediction file: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/rtdetr_l_drone_finetuned_predictions.csv

Running:
/usr/bin/python3 scripts/eval/run_detectors.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --models grounding_dino

----- live output starts -----
Preflight OK: 180 images, metadata=/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/evaluation/final_clean_full_curated_v1/test_drone_positive/metadata.csv

Running grounding_dino (grounding_dino) on 180 images...
FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
final text_encoder_type: bert-base-uncased

Inference grounding_dino:   0%|          | 0/180 [00:00<?, ?it/s]FutureWarning: The `device` argument is deprecated and will be removed in v5 of Transformers.
UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
UserWarning: None of the inputs have requires_grad=True. Gradients will be None
FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
FutureWarning: The `device` argument is deprecated and will be removed in v5 of Transformers.
UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
UserWarning: None of the inputs have requires_grad=True. Gradients will be None
FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.

Inference grounding_dino:   1%|          | 1/180 [00:04<12:51,  4.31s/it]
Inference grounding_dino:   1%|          | 2/180 [00:04<06:08,  2.07s/it]
Inference grounding_dino:   2%|▏         | 3/180 [00:05<03:56,  1.34s/it]
Inference grounding_dino:   2%|▏         | 4/180 [00:05<02:55,  1.00it/s]
Inference grounding_dino:   3%|▎         | 5/180 [00:06<02:20,  1.24it/s]
Inference grounding_dino:   3%|▎         | 6/180 [00:06<01:59,  1.46it/s]
Inference grounding_dino:   4%|▍         | 7/180 [00:07<01:46,  1.62it/s]
Inference grounding_dino:   4%|▍         | 8/180 [00:07<01:37,  1.76it/s]
Inference grounding_dino:   5%|▌         | 9/180 [00:08<01:32,  1.86it/s]
Inference grounding_dino:   6%|▌         | 10/180 [00:08<01:28,  1.92it/s]
Inference grounding_dino:   6%|▌         | 11/180 [00:09<01:26,  1.95it/s]
Inference grounding_dino:   7%|▋         | 12/180 [00:09<01:23,  2.00it/s]
Inference grounding_dino:   7%|▋         | 13/180 [00:10<01:22,  2.04it/s]
Inference grounding_dino:   8%|▊         | 14/180 [00:10<01:20,  2.07it/s]
Inference grounding_dino:   8%|▊         | 15/180 [00:10<01:18,  2.10it/s]
Inference grounding_dino:   9%|▉         | 16/180 [00:11<01:18,  2.09it/s]
Inference grounding_dino:   9%|▉         | 17/180 [00:11<01:17,  2.12it/s]
Inference grounding_dino:  10%|█         | 18/180 [00:12<01:16,  2.12it/s]
Inference grounding_dino:  11%|█         | 19/180 [00:12<01:15,  2.13it/s]
Inference grounding_dino:  11%|█         | 20/180 [00:13<01:14,  2.13it/s]
Inference grounding_dino:  12%|█▏        | 21/180 [00:13<01:14,  2.14it/s]
Inference grounding_dino:  12%|█▏        | 22/180 [00:14<01:13,  2.15it/s]
Inference grounding_dino:  13%|█▎        | 23/180 [00:14<01:14,  2.12it/s]
Inference grounding_dino:  13%|█▎        | 24/180 [00:15<01:13,  2.12it/s]
Inference grounding_dino:  14%|█▍        | 25/180 [00:15<01:12,  2.14it/s]
Inference grounding_dino:  14%|█▍        | 26/180 [00:16<01:11,  2.15it/s]
Inference grounding_dino:  15%|█▌        | 27/180 [00:16<01:10,  2.16it/s]
Inference grounding_dino:  16%|█▌        | 28/180 [00:16<01:10,  2.17it/s]
Inference grounding_dino:  16%|█▌        | 29/180 [00:17<01:09,  2.17it/s]
Inference grounding_dino:  17%|█▋        | 30/180 [00:17<01:08,  2.18it/s]
Inference grounding_dino:  17%|█▋        | 31/180 [00:18<01:08,  2.18it/s]
Inference grounding_dino:  18%|█▊        | 32/180 [00:18<01:08,  2.17it/s]
Inference grounding_dino:  18%|█▊        | 33/180 [00:19<01:07,  2.18it/s]
Inference grounding_dino:  19%|█▉        | 34/180 [00:19<01:07,  2.17it/s]
Inference grounding_dino:  19%|█▉        | 35/180 [00:20<01:06,  2.17it/s]
Inference grounding_dino:  20%|██        | 36/180 [00:20<01:07,  2.15it/s]
Inference grounding_dino:  21%|██        | 37/180 [00:21<01:06,  2.15it/s]
Inference grounding_dino:  21%|██        | 38/180 [00:21<01:06,  2.14it/s]
Inference grounding_dino:  22%|██▏       | 39/180 [00:22<01:05,  2.15it/s]
Inference grounding_dino:  22%|██▏       | 40/180 [00:22<01:05,  2.14it/s]
Inference grounding_dino:  23%|██▎       | 41/180 [00:23<01:04,  2.14it/s]
Inference grounding_dino:  23%|██▎       | 42/180 [00:23<01:04,  2.15it/s]
Inference grounding_dino:  24%|██▍       | 43/180 [00:23<01:03,  2.15it/s]
Inference grounding_dino:  24%|██▍       | 44/180 [00:24<01:03,  2.15it/s]
Inference grounding_dino:  25%|██▌       | 45/180 [00:24<01:02,  2.15it/s]
Inference grounding_dino:  26%|██▌       | 46/180 [00:25<01:02,  2.16it/s]
Inference grounding_dino:  26%|██▌       | 47/180 [00:25<01:01,  2.15it/s]
Inference grounding_dino:  27%|██▋       | 48/180 [00:26<01:01,  2.15it/s]
Inference grounding_dino:  27%|██▋       | 49/180 [00:26<01:00,  2.16it/s]
Inference grounding_dino:  28%|██▊       | 50/180 [00:27<01:00,  2.16it/s]
Inference grounding_dino:  28%|██▊       | 51/180 [00:27<00:59,  2.15it/s]
Inference grounding_dino:  29%|██▉       | 52/180 [00:28<00:59,  2.15it/s]
Inference grounding_dino:  29%|██▉       | 53/180 [00:28<00:59,  2.14it/s]
Inference grounding_dino:  30%|███       | 54/180 [00:29<00:59,  2.13it/s]
Inference grounding_dino:  31%|███       | 55/180 [00:29<00:58,  2.13it/s]
Inference grounding_dino:  31%|███       | 56/180 [00:30<00:58,  2.13it/s]
Inference grounding_dino:  32%|███▏      | 57/180 [00:30<00:57,  2.13it/s]
Inference grounding_dino:  32%|███▏      | 58/180 [00:30<00:56,  2.14it/s]
Inference grounding_dino:  33%|███▎      | 59/180 [00:31<00:56,  2.15it/s]
Inference grounding_dino:  33%|███▎      | 60/180 [00:31<00:55,  2.16it/s]
Inference grounding_dino:  34%|███▍      | 61/180 [00:32<00:55,  2.16it/s]
Inference grounding_dino:  34%|███▍      | 62/180 [00:32<00:54,  2.17it/s]
Inference grounding_dino:  35%|███▌      | 63/180 [00:33<00:54,  2.15it/s]
Inference grounding_dino:  36%|███▌      | 64/180 [00:33<00:53,  2.16it/s]
Inference grounding_dino:  36%|███▌      | 65/180 [00:34<00:53,  2.16it/s]
Inference grounding_dino:  37%|███▋      | 66/180 [00:34<00:52,  2.16it/s]
Inference grounding_dino:  37%|███▋      | 67/180 [00:35<00:52,  2.13it/s]
Inference grounding_dino:  38%|███▊      | 68/180 [00:35<00:52,  2.13it/s]
Inference grounding_dino:  38%|███▊      | 69/180 [00:36<00:51,  2.14it/s]
Inference grounding_dino:  39%|███▉      | 70/180 [00:36<00:50,  2.16it/s]
Inference grounding_dino:  39%|███▉      | 71/180 [00:36<00:50,  2.15it/s]
Inference grounding_dino:  40%|████      | 72/180 [00:37<00:50,  2.14it/s]
Inference grounding_dino:  41%|████      | 73/180 [00:37<00:49,  2.15it/s]
Inference grounding_dino:  41%|████      | 74/180 [00:38<00:49,  2.15it/s]
Inference grounding_dino:  42%|████▏     | 75/180 [00:38<00:48,  2.16it/s]
Inference grounding_dino:  42%|████▏     | 76/180 [00:39<00:47,  2.17it/s]
Inference grounding_dino:  43%|████▎     | 77/180 [00:39<00:47,  2.17it/s]
Inference grounding_dino:  43%|████▎     | 78/180 [00:40<00:46,  2.17it/s]
Inference grounding_dino:  44%|████▍     | 79/180 [00:40<00:46,  2.17it/s]
Inference grounding_dino:  44%|████▍     | 80/180 [00:41<00:46,  2.17it/s]
Inference grounding_dino:  45%|████▌     | 81/180 [00:41<00:45,  2.17it/s]
Inference grounding_dino:  46%|████▌     | 82/180 [00:42<00:45,  2.16it/s]
Inference grounding_dino:  46%|████▌     | 83/180 [00:42<00:44,  2.16it/s]
Inference grounding_dino:  47%|████▋     | 84/180 [00:42<00:44,  2.16it/s]
Inference grounding_dino:  47%|████▋     | 85/180 [00:43<00:43,  2.17it/s]
Inference grounding_dino:  48%|████▊     | 86/180 [00:43<00:43,  2.16it/s]
Inference grounding_dino:  48%|████▊     | 87/180 [00:44<00:43,  2.16it/s]
Inference grounding_dino:  49%|████▉     | 88/180 [00:44<00:42,  2.16it/s]
Inference grounding_dino:  49%|████▉     | 89/180 [00:45<00:42,  2.16it/s]
Inference grounding_dino:  50%|█████     | 90/180 [00:45<00:41,  2.16it/s]
Inference grounding_dino:  51%|█████     | 91/180 [00:46<00:41,  2.15it/s]
Inference grounding_dino:  51%|█████     | 92/180 [00:46<00:41,  2.14it/s]
Inference grounding_dino:  52%|█████▏    | 93/180 [00:47<00:40,  2.15it/s]
Inference grounding_dino:  52%|█████▏    | 94/180 [00:47<00:39,  2.16it/s]
Inference grounding_dino:  53%|█████▎    | 95/180 [00:48<00:39,  2.15it/s]
Inference grounding_dino:  53%|█████▎    | 96/180 [00:48<00:39,  2.15it/s]
Inference grounding_dino:  54%|█████▍    | 97/180 [00:49<00:38,  2.15it/s]
Inference grounding_dino:  54%|█████▍    | 98/180 [00:49<00:37,  2.16it/s]
Inference grounding_dino:  55%|█████▌    | 99/180 [00:49<00:37,  2.17it/s]
Inference grounding_dino:  56%|█████▌    | 100/180 [00:50<00:37,  2.15it/s]
Inference grounding_dino:  56%|█████▌    | 101/180 [00:50<00:36,  2.16it/s]
Inference grounding_dino:  57%|█████▋    | 102/180 [00:51<00:35,  2.17it/s]
Inference grounding_dino:  57%|█████▋    | 103/180 [00:51<00:35,  2.17it/s]
Inference grounding_dino:  58%|█████▊    | 104/180 [00:52<00:34,  2.18it/s]
Inference grounding_dino:  58%|█████▊    | 105/180 [00:52<00:34,  2.19it/s]
Inference grounding_dino:  59%|█████▉    | 106/180 [00:53<00:34,  2.17it/s]
Inference grounding_dino:  59%|█████▉    | 107/180 [00:53<00:34,  2.14it/s]
Inference grounding_dino:  60%|██████    | 108/180 [00:54<00:33,  2.16it/s]
Inference grounding_dino:  61%|██████    | 109/180 [00:54<00:32,  2.17it/s]
Inference grounding_dino:  61%|██████    | 110/180 [00:54<00:32,  2.18it/s]
Inference grounding_dino:  62%|██████▏   | 111/180 [00:55<00:31,  2.18it/s]
Inference grounding_dino:  62%|██████▏   | 112/180 [00:55<00:31,  2.18it/s]
Inference grounding_dino:  63%|██████▎   | 113/180 [00:56<00:30,  2.18it/s]
Inference grounding_dino:  63%|██████▎   | 114/180 [00:56<00:30,  2.19it/s]
Inference grounding_dino:  64%|██████▍   | 115/180 [00:57<00:29,  2.18it/s]
Inference grounding_dino:  64%|██████▍   | 116/180 [00:57<00:29,  2.18it/s]
Inference grounding_dino:  65%|██████▌   | 117/180 [00:58<00:29,  2.17it/s]
Inference grounding_dino:  66%|██████▌   | 118/180 [00:58<00:28,  2.17it/s]
Inference grounding_dino:  66%|██████▌   | 119/180 [00:59<00:27,  2.18it/s]
Inference grounding_dino:  67%|██████▋   | 120/180 [00:59<00:27,  2.18it/s]
Inference grounding_dino:  67%|██████▋   | 121/180 [01:00<00:27,  2.18it/s]
Inference grounding_dino:  68%|██████▊   | 122/180 [01:00<00:26,  2.17it/s]
Inference grounding_dino:  68%|██████▊   | 123/180 [01:00<00:26,  2.16it/s]
Inference grounding_dino:  69%|██████▉   | 124/180 [01:01<00:25,  2.17it/s]
Inference grounding_dino:  69%|██████▉   | 125/180 [01:01<00:25,  2.16it/s]
Inference grounding_dino:  70%|███████   | 126/180 [01:02<00:24,  2.17it/s]
Inference grounding_dino:  71%|███████   | 127/180 [01:02<00:24,  2.16it/s]
Inference grounding_dino:  71%|███████   | 128/180 [01:03<00:24,  2.17it/s]
Inference grounding_dino:  72%|███████▏  | 129/180 [01:03<00:23,  2.16it/s]
Inference grounding_dino:  72%|███████▏  | 130/180 [01:04<00:23,  2.16it/s]
Inference grounding_dino:  73%|███████▎  | 131/180 [01:04<00:22,  2.15it/s]
Inference grounding_dino:  73%|███████▎  | 132/180 [01:05<00:22,  2.16it/s]
Inference grounding_dino:  74%|███████▍  | 133/180 [01:05<00:21,  2.16it/s]
Inference grounding_dino:  74%|███████▍  | 134/180 [01:06<00:21,  2.17it/s]
Inference grounding_dino:  75%|███████▌  | 135/180 [01:06<00:20,  2.18it/s]
Inference grounding_dino:  76%|███████▌  | 136/180 [01:06<00:20,  2.17it/s]
Inference grounding_dino:  76%|███████▌  | 137/180 [01:07<00:19,  2.18it/s]
Inference grounding_dino:  77%|███████▋  | 138/180 [01:07<00:19,  2.18it/s]
Inference grounding_dino:  77%|███████▋  | 139/180 [01:08<00:18,  2.16it/s]
Inference grounding_dino:  78%|███████▊  | 140/180 [01:08<00:18,  2.16it/s]
Inference grounding_dino:  78%|███████▊  | 141/180 [01:09<00:18,  2.17it/s]
Inference grounding_dino:  79%|███████▉  | 142/180 [01:09<00:17,  2.17it/s]
Inference grounding_dino:  79%|███████▉  | 143/180 [01:10<00:17,  2.17it/s]
Inference grounding_dino:  80%|████████  | 144/180 [01:10<00:16,  2.18it/s]
Inference grounding_dino:  81%|████████  | 145/180 [01:11<00:16,  2.16it/s]
Inference grounding_dino:  81%|████████  | 146/180 [01:11<00:15,  2.17it/s]
Inference grounding_dino:  82%|████████▏ | 147/180 [01:12<00:15,  2.17it/s]
Inference grounding_dino:  82%|████████▏ | 148/180 [01:12<00:14,  2.17it/s]
Inference grounding_dino:  83%|████████▎ | 149/180 [01:12<00:14,  2.16it/s]
Inference grounding_dino:  83%|████████▎ | 150/180 [01:13<00:13,  2.16it/s]
Inference grounding_dino:  84%|████████▍ | 151/180 [01:13<00:13,  2.16it/s]
Inference grounding_dino:  84%|████████▍ | 152/180 [01:14<00:12,  2.18it/s]
Inference grounding_dino:  85%|████████▌ | 153/180 [01:14<00:12,  2.19it/s]
Inference grounding_dino:  86%|████████▌ | 154/180 [01:15<00:11,  2.18it/s]
Inference grounding_dino:  86%|████████▌ | 155/180 [01:15<00:11,  2.19it/s]
Inference grounding_dino:  87%|████████▋ | 156/180 [01:16<00:10,  2.19it/s]
Inference grounding_dino:  87%|████████▋ | 157/180 [01:16<00:10,  2.18it/s]
Inference grounding_dino:  88%|████████▊ | 158/180 [01:17<00:10,  2.17it/s]
Inference grounding_dino:  88%|████████▊ | 159/180 [01:17<00:09,  2.17it/s]
Inference grounding_dino:  89%|████████▉ | 160/180 [01:18<00:09,  2.17it/s]
Inference grounding_dino:  89%|████████▉ | 161/180 [01:18<00:08,  2.17it/s]
Inference grounding_dino:  90%|█████████ | 162/180 [01:18<00:08,  2.16it/s]
Inference grounding_dino:  91%|█████████ | 163/180 [01:19<00:07,  2.15it/s]
Inference grounding_dino:  91%|█████████ | 164/180 [01:19<00:07,  2.15it/s]
Inference grounding_dino:  92%|█████████▏| 165/180 [01:20<00:06,  2.15it/s]
Inference grounding_dino:  92%|█████████▏| 166/180 [01:20<00:06,  2.16it/s]
Inference grounding_dino:  93%|█████████▎| 167/180 [01:21<00:06,  2.15it/s]
Inference grounding_dino:  93%|█████████▎| 168/180 [01:21<00:05,  2.16it/s]
Inference grounding_dino:  94%|█████████▍| 169/180 [01:22<00:05,  2.16it/s]
Inference grounding_dino:  94%|█████████▍| 170/180 [01:22<00:04,  2.17it/s]
Inference grounding_dino:  95%|█████████▌| 171/180 [01:23<00:04,  2.18it/s]
Inference grounding_dino:  96%|█████████▌| 172/180 [01:23<00:03,  2.18it/s]
Inference grounding_dino:  96%|█████████▌| 173/180 [01:24<00:03,  2.18it/s]
Inference grounding_dino:  97%|█████████▋| 174/180 [01:24<00:02,  2.18it/s]
Inference grounding_dino:  97%|█████████▋| 175/180 [01:24<00:02,  2.17it/s]
Inference grounding_dino:  98%|█████████▊| 176/180 [01:25<00:01,  2.17it/s]
Inference grounding_dino:  98%|█████████▊| 177/180 [01:25<00:01,  2.16it/s]
Inference grounding_dino:  99%|█████████▉| 178/180 [01:26<00:00,  2.16it/s]
Inference grounding_dino:  99%|█████████▉| 179/180 [01:26<00:00,  2.16it/s]
Inference grounding_dino: 100%|██████████| 180/180 [01:27<00:00,  2.17it/s]
Inference grounding_dino: 100%|██████████| 180/180 [01:27<00:00,  2.06it/s]
Wrote 2061 predictions -> /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/grounding_dino_predictions.csv

Wrote run info: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/run_info.json

----- live output ended -----
Return code: 0
Elapsed time: 1.7 minutes

Running:
/usr/bin/python3 scripts/eval/run_detectors.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --models yolo11n_drone_finetuned

----- live output starts -----
Preflight OK: 180 images, metadata=/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/evaluation/final_clean_full_curated_v1/test_drone_positive/metadata.csv

Running yolo11n_drone_finetuned (ultralytics_yolo) on 180 images...

Inference yolo11n_drone_finetuned:   0%|          | 0/180 [00:00<?, ?it/s]
Inference yolo11n_drone_finetuned:   1%|          | 1/180 [00:00<02:49,  1.06it/s]
Inference yolo11n_drone_finetuned:   3%|▎         | 5/180 [00:01<00:28,  6.11it/s]
Inference yolo11n_drone_finetuned:   5%|▌         | 9/180 [00:01<00:14, 11.41it/s]
Inference yolo11n_drone_finetuned:   7%|▋         | 13/180 [00:01<00:10, 16.43it/s]
Inference yolo11n_drone_finetuned:   9%|▉         | 17/180 [00:01<00:07, 21.16it/s]
Inference yolo11n_drone_finetuned:  12%|█▏        | 22/180 [00:01<00:05, 26.42it/s]
Inference yolo11n_drone_finetuned:  15%|█▌        | 27/180 [00:01<00:05, 30.43it/s]
Inference yolo11n_drone_finetuned:  18%|█▊        | 32/180 [00:01<00:04, 33.41it/s]
Inference yolo11n_drone_finetuned:  21%|██        | 37/180 [00:01<00:03, 35.83it/s]
Inference yolo11n_drone_finetuned:  23%|██▎       | 42/180 [00:01<00:03, 37.45it/s]
Inference yolo11n_drone_finetuned:  26%|██▌       | 47/180 [00:02<00:03, 38.06it/s]
Inference yolo11n_drone_finetuned:  29%|██▉       | 52/180 [00:02<00:03, 37.87it/s]
Inference yolo11n_drone_finetuned:  31%|███       | 56/180 [00:02<00:03, 37.89it/s]
Inference yolo11n_drone_finetuned:  33%|███▎      | 60/180 [00:02<00:03, 38.20it/s]
Inference yolo11n_drone_finetuned:  36%|███▌      | 64/180 [00:02<00:03, 38.53it/s]
Inference yolo11n_drone_finetuned:  38%|███▊      | 68/180 [00:02<00:03, 36.58it/s]
Inference yolo11n_drone_finetuned:  41%|████      | 73/180 [00:02<00:02, 37.75it/s]
Inference yolo11n_drone_finetuned:  43%|████▎     | 77/180 [00:02<00:02, 38.35it/s]
Inference yolo11n_drone_finetuned:  45%|████▌     | 81/180 [00:02<00:02, 38.78it/s]
Inference yolo11n_drone_finetuned:  47%|████▋     | 85/180 [00:03<00:02, 38.82it/s]
Inference yolo11n_drone_finetuned:  49%|████▉     | 89/180 [00:03<00:02, 38.22it/s]

In [ ]:
# 13) Inspect prediction CSVs by evaluation subset
import pandas as pd

for eval_name, job in EVAL_JOBS.items():
    pred_dir = job["output_root"] / "predictions"
    print("\n" + "#" * 100)
    print("EVAL SUBSET:", eval_name)
    print("Prediction directory:", pred_dir)
    print("#" * 100)

    if not pred_dir.exists():
        print("Prediction directory does not exist.")
        continue

    for csv_path in sorted(pred_dir.glob("*_predictions.csv")):
        df = pd.read_csv(csv_path)
        print("\n" + "=" * 80)
        print(csv_path.name)
        print("shape:", df.shape)
        if "model_name" in df.columns and len(df):
            print("model_name:", df["model_name"].unique())
        if "confidence" in df.columns and len(df):
            print("confidence min/mean/max:", df["confidence"].min(), df["confidence"].mean(), df["confidence"].max())
        if "image_id" in df.columns and len(df):
            print("first image_ids:", df["image_id"].head().tolist())
        display(df.head())

####################################################################################################
EVAL SUBSET: test_drone_positive
Prediction directory: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions
####################################################################################################

================================================================================
grounding_dino_predictions.csv
shape: (2061, 14)
model_name: ['grounding_dino']
confidence min/mean/max: 0.200184 0.35945766424065984 0.9426
first image_ids: ['img_000031.png', 'img_000031.png', 'img_000031.png', 'img_000031.png', 'img_000031.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.875487,212.90,193.82,244.68,212.37,31.78,18.55,drone,drone
1,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.897025,212.87,193.87,244.73,212.44,31.87,18.57,quadcopter,quadcopter
2,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.826014,212.48,193.10,245.17,212.92,32.69,19.82,unmanned aerial vehicle,unmanned aerial vehicle
3,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.614465,211.35,190.64,246.53,214.52,35.18,23.88,small drone in the sky,small drone
4,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.473155,1.74,1.40,638.24,341.38,636.50,339.98,small drone in the sky,sky

================================================================================
rtdetr_l_drone_finetuned_predictions.csv
shape: (5862, 14)
model_name: ['rtdetr_l_drone_finetuned']
confidence min/mean/max: 0.050003 0.09204810252473558 0.790581
first image_ids: ['img_000031.png', 'img_000031.png', 'img_000031.png', 'img_000031.png', 'img_000031.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.720437,208.16,189.84,248.97,217.50,40.81,27.66,NaN,drone
1,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.178034,621.37,264.62,638.23,280.88,16.86,16.26,NaN,drone
2,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.137040,623.49,266.63,637.95,278.52,14.46,11.90,NaN,drone
3,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.115599,624.51,321.42,637.64,334.95,13.13,13.52,NaN,drone
4,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.101073,507.00,613.21,526.82,627.98,19.81,14.78,NaN,drone

================================================================================
yolo11n_drone_finetuned_predictions.csv
shape: (313, 14)
model_name: ['yolo11n_drone_finetuned']
confidence min/mean/max: 0.050284 0.2728070127795527 0.779578
first image_ids: ['img_000031.png', 'img_000031.png', 'img_000077.png', 'img_000077.png', 'img_000077.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.645613,204.08,188.99,255.60,219.58,51.52,30.59,NaN,drone
1,img_000031.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.110507,198.63,186.04,263.89,226.63,65.25,40.59,NaN,drone
2,img_000077.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.562787,345.65,66.83,357.96,74.26,12.31,7.43,NaN,drone
3,img_000077.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.122260,343.65,65.45,360.18,76.65,16.53,11.20,NaN,drone
4,img_000077.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.068833,39.60,298.07,88.92,327.19,49.31,29.11,NaN,drone

####################################################################################################
EVAL SUBSET: test_hard_negative
Prediction directory: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions
####################################################################################################

================================================================================
grounding_dino_predictions.csv
shape: (1873, 14)
model_name: ['grounding_dino']
confidence min/mean/max: 0.200064 0.4005129295248265 0.943309
first image_ids: ['img_000004.png', 'img_000004.png', 'img_000004.png', 'img_000004.png', 'img_000004.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.666233,271.53,47.55,330.76,73.88,59.23,26.33,drone,drone
1,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.388497,107.09,367.82,223.16,452.57,116.06,84.74,drone,drone
2,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.254694,115.00,396.76,178.75,451.84,63.75,55.08,drone,drone
3,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.243434,318.66,381.77,350.82,413.16,32.16,31.39,drone,drone
4,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.203212,142.86,376.92,185.04,419.97,42.18,43.05,drone,drone

================================================================================
rtdetr_l_drone_finetuned_predictions.csv
shape: (7218, 14)
model_name: ['rtdetr_l_drone_finetuned']
confidence min/mean/max: 0.05 0.08611278706012745 0.667937
first image_ids: ['img_000004.png', 'img_000004.png', 'img_000004.png', 'img_000004.png', 'img_000004.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.181296,618.54,448.52,627.00,454.30,8.46,5.78,NaN,drone
1,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.176832,222.13,575.35,229.66,580.40,7.53,5.05,NaN,drone
2,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.174523,609.04,313.58,615.04,318.17,6.01,4.59,NaN,drone
3,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.171670,364.78,459.28,372.70,464.57,7.92,5.30,NaN,drone
4,img_000004.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.160633,466.37,479.86,474.37,486.45,8.00,6.59,NaN,drone

================================================================================
yolo11n_drone_finetuned_predictions.csv
shape: (107, 14)
model_name: ['yolo11n_drone_finetuned']
confidence min/mean/max: 0.050265 0.1394916074766355 0.569142
first image_ids: ['img_000045.png', 'img_000069.png', 'img_000137.png', 'img_000182.png', 'img_000182.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000045.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.246330,28.76,39.84,61.24,59.91,32.48,20.08,NaN,drone
1,img_000069.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.078123,513.75,243.69,522.14,248.67,8.40,4.98,NaN,drone
2,img_000137.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.068383,21.51,230.60,41.13,242.69,19.61,12.10,NaN,drone
3,img_000182.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.092631,0.00,11.92,37.19,51.23,37.19,39.31,NaN,drone
4,img_000182.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.052656,318.49,268.49,330.30,276.22,11.81,7.73,NaN,drone

####################################################################################################
EVAL SUBSET: test_mixed
Prediction directory: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions
####################################################################################################

================================================================================
grounding_dino_predictions.csv
shape: (1999, 14)
model_name: ['grounding_dino']
confidence min/mean/max: 0.200046 0.3984674812406203 0.934777
first image_ids: ['img_000020.png', 'img_000020.png', 'img_000020.png', 'img_000020.png', 'img_000020.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.703800,244.20,177.67,274.82,199.48,30.63,21.82,drone,drone
1,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.671314,50.46,256.54,69.35,285.16,18.89,28.62,drone,drone
2,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.661020,243.95,177.77,274.87,199.63,30.91,21.85,quadcopter,quadcopter
3,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.639239,50.30,256.49,69.43,285.25,19.13,28.76,quadcopter,quadcopter
4,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,grounding_dino,0,drone,0.463423,243.59,176.94,275.21,200.72,31.62,23.78,unmanned aerial vehicle,unmanned aerial vehicle

================================================================================
rtdetr_l_drone_finetuned_predictions.csv
shape: (6401, 14)
model_name: ['rtdetr_l_drone_finetuned']
confidence min/mean/max: 0.05 0.09401114888298705 0.781238
first image_ids: ['img_000020.png', 'img_000020.png', 'img_000020.png', 'img_000020.png', 'img_000020.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.758449,237.98,173.56,282.19,205.20,44.21,31.64,NaN,drone
1,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.272862,578.79,421.19,586.95,426.60,8.15,5.41,NaN,drone
2,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.258142,234.55,441.82,241.54,446.37,6.99,4.56,NaN,drone
3,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.182025,454.67,421.11,460.59,425.30,5.92,4.20,NaN,drone
4,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,rtdetr_l_drone_finetuned,0,drone,0.167585,483.76,439.62,505.15,458.64,21.38,19.02,NaN,drone

================================================================================
yolo11n_drone_finetuned_predictions.csv
shape: (382, 14)
model_name: ['yolo11n_drone_finetuned']
confidence min/mean/max: 0.050366 0.2563887565445026 0.770713
first image_ids: ['img_000020.png', 'img_000020.png', 'img_000020.png', 'img_000047.png', 'img_000047.png']

,image_id,image_path,model_name,pred_class_id,pred_class_name,confidence,x1,y1,x2,y2,width,height,prompt,raw_label
0,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.683181,234.66,174.02,288.34,206.18,53.68,32.16,NaN,drone
1,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.288453,231.43,171.16,294.19,210.67,62.77,39.51,NaN,drone
2,img_000020.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.060236,238.93,177.33,282.34,202.61,43.42,25.28,NaN,drone
3,img_000047.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.377058,30.58,186.77,50.42,199.87,19.84,13.09,NaN,drone
4,img_000047.png,/content/drive/MyDrive/Synthetic Stress Testin...,yolo11n_drone_finetuned,0,drone,0.306000,367.19,110.77,375.87,116.25,8.68,5.48,NaN,drone

In [ ]:
# #Fix the evaluator
# from pathlib import Path

# metrics_py = PROJECT_ROOT / "src/drone_stress/detector_eval/metrics.py"
# print("Patching:", metrics_py)
# text = metrics_py.read_text()

# old = """old = pd.read_csv(win_long_path(path))"""

# new = """try:
#             old = pd.read_csv(win_long_path(path))
#         except pd.errors.EmptyDataError:
#             old = pd.DataFrame()
#         except Exception as e:
#             print(f"WARNING: failed to read existing metrics CSV {path}: {e}")
#             old = pd.DataFrame()"""

# if old not in text:
#     print("Exact target line not found. Showing nearby lines containing pd.read_csv:")
#     for i, line in enumerate(text.splitlines(), start=1):
#         if "pd.read_csv" in line:
#             print(i, line)
# else:
#     text = text.replace(old, new)
#     metrics_py.write_text(text)
#     print("✅ Patched metrics.py to tolerate empty/corrupt existing CSV files.")

Patching: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py
✅ Patched metrics.py to tolerate empty/corrupt existing CSV files.

In [ ]:
# #clean the old broken metrics files
# from pathlib import Path

# for eval_name, job in EVAL_JOBS.items():
#     metrics_dir = job["output_root"] / "metrics"
#     print("\nCleaning:", metrics_dir)
#     if metrics_dir.exists():
#         for p in metrics_dir.glob("*.csv"):
#             print(" deleting", p.name)
#             p.unlink()

# combined_metrics_dir = EVAL_OUTPUT_ROOT / "combined_metrics"
# if combined_metrics_dir.exists():
#     for p in combined_metrics_dir.glob("*.csv"):
#         print(" deleting combined", p.name)
#         p.unlink()

Cleaning: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/metrics
 deleting grounding_dino_matched_predictions.csv
 deleting grounding_dino_image_level_metrics.csv
 deleting grounding_dino_summary_metrics.csv
 deleting grounding_dino_grouped_metrics.csv
 deleting recall_by_subset.csv
 deleting recall_by_size_noise_blur.csv
 deleting false_positive_by_distractor_type.csv
 deleting recall_by_distractor_present.csv
 deleting image_level_metrics.csv
 deleting matched_predictions.csv
 deleting yolo11n_drone_finetuned_matched_predictions.csv
 deleting yolo11n_drone_finetuned_image_level_metrics.csv
 deleting yolo11n_drone_finetuned_summary_metrics.csv
 deleting yolo11n_drone_finetuned_grouped_metrics.csv
 deleting rtdetr_l_drone_finetuned_matched_predictions.csv
 deleting rtdetr_l_drone_finetuned_image_level_metrics.csv
 deleting rtdetr_l_drone_finetuned_summary_metrics.csv
 deleting rtdetr_l_drone_finetuned_grouped_metrics.csv
 deleting summary_by_model_with_eval_subset.csv

Cleaning: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics
 deleting grounding_dino_matched_predictions.csv
 deleting grounding_dino_image_level_metrics.csv
 deleting grounding_dino_summary_metrics.csv
 deleting grounding_dino_grouped_metrics.csv
 deleting recall_by_subset.csv
 deleting recall_by_size_noise_blur.csv
 deleting false_positive_by_distractor_type.csv
 deleting recall_by_distractor_present.csv
 deleting image_level_metrics.csv
 deleting matched_predictions.csv
 deleting yolo11n_drone_finetuned_matched_predictions.csv
 deleting yolo11n_drone_finetuned_image_level_metrics.csv
 deleting yolo11n_drone_finetuned_summary_metrics.csv
 deleting yolo11n_drone_finetuned_grouped_metrics.csv
 deleting rtdetr_l_drone_finetuned_matched_predictions.csv
 deleting rtdetr_l_drone_finetuned_image_level_metrics.csv
 deleting rtdetr_l_drone_finetuned_summary_metrics.csv
 deleting rtdetr_l_drone_finetuned_grouped_metrics.csv
 deleting summary_by_model_with_eval_subset.csv

Cleaning: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics
 deleting grounding_dino_matched_predictions.csv
 deleting grounding_dino_image_level_metrics.csv
 deleting grounding_dino_summary_metrics.csv
 deleting grounding_dino_grouped_metrics.csv
 deleting recall_by_subset.csv
 deleting recall_by_size_noise_blur.csv
 deleting false_positive_by_distractor_type.csv
 deleting recall_by_distractor_present.csv
 deleting image_level_metrics.csv
 deleting matched_predictions.csv
 deleting yolo11n_drone_finetuned_matched_predictions.csv
 deleting yolo11n_drone_finetuned_image_level_metrics.csv
 deleting yolo11n_drone_finetuned_summary_metrics.csv
 deleting yolo11n_drone_finetuned_grouped_metrics.csv
 deleting rtdetr_l_drone_finetuned_matched_predictions.csv
 deleting rtdetr_l_drone_finetuned_image_level_metrics.csv
 deleting rtdetr_l_drone_finetuned_summary_metrics.csv
 deleting rtdetr_l_drone_finetuned_grouped_metrics.csv
 deleting summary_by_model_with_eval_subset.csv
 deleting combined summary_by_model_by_eval_subset.csv

In [ ]:
#fix metrics.py identation
from pathlib import Path
import re
import py_compile

metrics_py = PROJECT_ROOT / "src/drone_stress/detector_eval/metrics.py"
print("Repairing:", metrics_py)

text = metrics_py.read_text()

# Fix the malformed try/except block around:
# old = pd.read_csv(win_long_path(path))
pattern = re.compile(
    r'(?m)^(?P<indent>\s*)try:\n'
    r'\s*old = pd\.read_csv\(win_long_path\(path\)\)\n'
    r'\s*except pd\.errors\.EmptyDataError:\n'
    r'\s*old = pd\.DataFrame\(\)\n'
    r'\s*except Exception as e:\n'
    r'\s*print\(f"WARNING: failed to read existing metrics CSV \{path\}: \{e\}"\)\n'
    r'\s*old = pd\.DataFrame\(\)'
)

def repl(m):
    indent = m.group("indent")
    return (
        f"{indent}try:\n"
        f"{indent}    old = pd.read_csv(win_long_path(path))\n"
        f"{indent}except pd.errors.EmptyDataError:\n"
        f"{indent}    old = pd.DataFrame()\n"
        f"{indent}except Exception as e:\n"
        f"{indent}    print(f\"WARNING: failed to read existing metrics CSV {{path}}: {{e}}\")\n"
        f"{indent}    old = pd.DataFrame()"
    )

new_text, n = pattern.subn(repl, text)

if n == 0:
    print("Regex did not find the malformed block. Showing lines 330-350:")
    lines = text.splitlines()
    for i in range(329, min(350, len(lines))):
        print(f"{i+1}: {lines[i]}")
    raise RuntimeError("Patch target not found. Paste the printed lines here.")

metrics_py.write_text(new_text)

# Verify syntax
py_compile.compile(str(metrics_py), doraise=True)

print("✅ metrics.py syntax repaired.")

Repairing: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py
✅ metrics.py syntax repaired.

In [ ]:
#Clean broken metrics
for eval_name, job in EVAL_JOBS.items():
    metrics_dir = job["output_root"] / "metrics"
    print("\nCleaning:", metrics_dir)
    if metrics_dir.exists():
        for p in metrics_dir.glob("*.csv"):
            print(" deleting", p.name)
            p.unlink()

combined_metrics_dir = EVAL_OUTPUT_ROOT / "combined_metrics"
if combined_metrics_dir.exists():
    for p in combined_metrics_dir.glob("*.csv"):
        print(" deleting combined", p.name)
        p.unlink()

Cleaning: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/metrics

Cleaning: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics

Cleaning: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics

In [ ]:
# 14) Metrics + prediction QA by held-out evaluation subset
# Writes one combined table with eval_subset, model_name, recall, FP rates/counts, etc.

import pandas as pd
from pathlib import Path

models = [
    "grounding_dino",
    "yolo11n_drone_finetuned",
    "rtdetr_l_drone_finetuned",
]

all_rows = []

for eval_name, job in EVAL_JOBS.items():
    print("\n" + "#" * 100)
    print("METRICS FOR EVAL SUBSET:", eval_name)
    print("#" * 100)

    metadata_df = pd.read_csv(job["dataset_root"] / "metadata.csv")
    n_target_present = int(metadata_df["target_present"].astype(bool).sum()) if "target_present" in metadata_df.columns else 0
    n_distractor_only = int((metadata_df["subset"] == "synthetic_distractor_only").sum()) if "subset" in metadata_df.columns else 0

    pred_dir = job["output_root"] / "predictions"
    metrics_dir = job["output_root"] / "metrics"
    metrics_dir.mkdir(parents=True, exist_ok=True)

    subset_rows = []

    for model in models:
        pred_csv = pred_dir / f"{model}_predictions.csv"
        print("\n" + "=" * 80)
        print("MODEL:", model)
        print("=" * 80)

        if not pred_csv.is_file():
            print("SKIP missing prediction file:", pred_csv)
            continue

        pred_df = pd.read_csv(pred_csv)
        print("prediction rows:", len(pred_df))

        if len(pred_df) == 0:
            print("Empty prediction CSV. Adding zero-detection metrics instead of crashing.")
            for iou_thr in [0.25, 0.50]:
                subset_rows.append({
                    "eval_subset": eval_name,
                    "source_subset": job["subset"],
                    "model_name": model,
                    "model_type": "empty_or_underconfident",
                    "iou_threshold": iou_thr,
                    "n_target_present": n_target_present,
                    "n_distractor_only": n_distractor_only,
                    "recall": 0.0,
                    "tp": 0,
                    "fn": n_target_present,
                    "mean_best_iou": 0.0,
                    "false_positive_image_rate": 0.0,
                    "fp_count": 0,
                    "note": "No predictions at configured inference threshold; likely undertrained or threshold too high.",
                })
            continue

        # Evaluate this model for this subset.
        result = run_command([
            sys.executable,
            "code/code/scripts/eval/evaluate_detector_predictions.py",
            "--config", str(job["config"]),
            "--predictions", str(pred_csv),
            "--project-root", str(PROJECT_ROOT),
        ], check=False)

        #if result.returncode == 0:
        rc = result if isinstance(result, int) else result.returncode

        if rc == 0:
            summary_path = metrics_dir / "summary_by_model.csv"
            if summary_path.exists():
                summary_df = pd.read_csv(summary_path)
                summary_df["eval_subset"] = eval_name
                summary_df["source_subset"] = job["subset"]
                subset_rows.extend(summary_df.to_dict("records"))
        else:
            print("Evaluation failed for this model; see output above.")
            continue

        # Visualization / prediction QA
        run_command([
            sys.executable,
            "code/code/scripts/eval/visualize_predictions.py",
            "--config", str(job["config"]),
            "--predictions", str(pred_csv),
            "--project-root", str(PROJECT_ROOT),
            "--num-samples", "12",
        ], check=False)

    subset_summary = pd.DataFrame(subset_rows)
    if len(subset_summary):
        subset_summary = subset_summary.drop_duplicates(
            subset=["eval_subset", "model_name", "iou_threshold"],
            keep="last",
        ).sort_values(["eval_subset", "model_name", "iou_threshold"]).reset_index(drop=True)

    subset_summary_path = metrics_dir / "summary_by_model_with_eval_subset.csv"
    subset_summary.to_csv(subset_summary_path, index=False)
    print("\nSubset summary written to:", subset_summary_path)
    display(subset_summary)

    all_rows.extend(subset_summary.to_dict("records"))

combined_summary = pd.DataFrame(all_rows)

if len(combined_summary):
    combined_summary = combined_summary.drop_duplicates(
        subset=["eval_subset", "model_name", "iou_threshold"],
        keep="last",
    ).sort_values(["eval_subset", "model_name", "iou_threshold"]).reset_index(drop=True)

combined_metrics_dir = EVAL_OUTPUT_ROOT / "combined_metrics"
combined_metrics_dir.mkdir(parents=True, exist_ok=True)

combined_path = combined_metrics_dir / "summary_by_model_by_eval_subset.csv"
combined_summary.to_csv(combined_path, index=False)

print("\nCombined final-clean summary written to:")
print(combined_path)
display(combined_summary)

# Optional pivots for quick comparison.
if len(combined_summary):
    print("\nRecall pivot:")
    display(combined_summary.pivot_table(
        index=["model_name", "iou_threshold"],
        columns="eval_subset",
        values="recall",
        aggfunc="first",
    ))

    print("\nFP count pivot:")
    display(combined_summary.pivot_table(
        index=["model_name", "iou_threshold"],
        columns="eval_subset",
        values="fp_count",
        aggfunc="first",
    ))

####################################################################################################
METRICS FOR EVAL SUBSET: test_drone_positive
####################################################################################################

================================================================================
MODEL: grounding_dino
================================================================================
prediction rows: 2061

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating grounding_dino from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/grounding_dino_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/metrics/summary_by_model.csv
Wrote 5 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/plots

Summary by model:
    model_name     model_type  iou_threshold  n_target_present  n_distractor_only   recall  tp  fn  mean_best_iou false_positive_image_rate  fp_count                                                      note
grounding_dino grounding_dino           0.25               180                  0 0.622222 112  68       0.399236                      None         0 Open-vocabulary drone prompts; boxes count as drone-like.
grounding_dino grounding_dino           0.50               180                  0 0.538889  97  83       0.366148                      None         0 Open-vocabulary drone prompts; boxes count as drone-like.

----- live output ended -----
Return code: 0
Elapsed time: 0.1 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Saved: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/visualizations/grounding_dino_prediction_qa.png
Legend: green=GT drone, orange=predictions

----- live output ended -----
Return code: 0
Elapsed time: 0.0 minutes

================================================================================
MODEL: yolo11n_drone_finetuned
================================================================================
prediction rows: 313

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating yolo11n_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/yolo11n_drone_finetuned_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/metrics/summary_by_model.csv
Wrote 6 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/plots

Summary by model:
             model_name       model_type  iou_threshold  n_target_present  n_distractor_only   recall  tp  fn  mean_best_iou false_positive_image_rate  fp_count                                                                note
yolo11n_drone_finetuned ultralytics_yolo           0.25               143                  0 0.916084 131  12       0.677089                      None         0 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']
yolo11n_drone_finetuned ultralytics_yolo           0.50               143                  0 0.860140 123  20       0.654746                      None         0 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']

----- live output ended -----
Return code: 0
Elapsed time: 0.1 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 154, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 124, in main
    label = f"{pr['prompt'][:20]} {pr.get('confidence',0):.2f}"
               ~~~~~~~~~~~~^^^^^
TypeError: 'float' object is not subscriptable

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes

================================================================================
MODEL: rtdetr_l_drone_finetuned
================================================================================
prediction rows: 5862

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating rtdetr_l_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/rtdetr_l_drone_finetuned_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/metrics/summary_by_model.csv
Wrote 7 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/plots

Summary by model:
              model_name         model_type  iou_threshold  n_target_present  n_distractor_only   recall  tp  fn  mean_best_iou false_positive_image_rate  fp_count                                                                note
rtdetr_l_drone_finetuned ultralytics_rtdetr           0.25               180                  0 0.816667 147  33       0.547084                      None         0 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']
rtdetr_l_drone_finetuned ultralytics_rtdetr           0.50               180                  0 0.700000 126  54       0.502650                      None         0 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']

----- live output ended -----
Return code: 0
Elapsed time: 0.1 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 154, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 124, in main
    label = f"{pr['prompt'][:20]} {pr.get('confidence',0):.2f}"
               ~~~~~~~~~~~~^^^^^
TypeError: 'float' object is not subscriptable

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes

Subset summary written to: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/metrics/summary_by_model_with_eval_subset.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset
0,grounding_dino,grounding_dino,0.25,180,0,0.622222,112,68,0.399236,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_drone_positive,synthetic_drone_positive
1,grounding_dino,grounding_dino,0.50,180,0,0.538889,97,83,0.366148,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_drone_positive,synthetic_drone_positive
2,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,180,0,0.816667,147,33,0.547084,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive
3,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,180,0,0.700000,126,54,0.502650,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive
4,yolo11n_drone_finetuned,ultralytics_yolo,0.25,143,0,0.916084,131,12,0.677089,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive
5,yolo11n_drone_finetuned,ultralytics_yolo,0.50,143,0,0.860140,123,20,0.654746,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive

####################################################################################################
METRICS FOR EVAL SUBSET: test_hard_negative
####################################################################################################

================================================================================
MODEL: grounding_dino
================================================================================
prediction rows: 1873

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating grounding_dino from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/grounding_dino_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics/summary_by_model.csv
Wrote 1 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/plots

Summary by model:
    model_name     model_type  iou_threshold  n_target_present  n_distractor_only recall  tp  fn mean_best_iou  false_positive_image_rate  fp_count                                                      note
grounding_dino grounding_dino           0.25                 0                180   None   0   0          None                        1.0      1873 Open-vocabulary drone prompts; boxes count as drone-like.
grounding_dino grounding_dino           0.50                 0                180   None   0   0          None                        1.0      1873 Open-vocabulary drone prompts; boxes count as drone-like.

----- live output ended -----
Return code: 0
Elapsed time: 0.0 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Saved: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/visualizations/grounding_dino_prediction_qa.png
Legend: green=GT drone, orange=predictions

----- live output ended -----
Return code: 0
Elapsed time: 0.0 minutes

================================================================================
MODEL: yolo11n_drone_finetuned
================================================================================
prediction rows: 107

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating yolo11n_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/yolo11n_drone_finetuned_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics/summary_by_model.csv
Wrote 1 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/plots

Summary by model:
             model_name       model_type  iou_threshold  n_target_present  n_distractor_only recall  tp  fn mean_best_iou  false_positive_image_rate  fp_count                                                                note
yolo11n_drone_finetuned ultralytics_yolo           0.25                 0                 62   None   0   0          None                        1.0       107 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']
yolo11n_drone_finetuned ultralytics_yolo           0.50                 0                 62   None   0   0          None                        1.0       107 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']

----- live output ended -----
Return code: 0
Elapsed time: 0.0 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 154, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 124, in main
    label = f"{pr['prompt'][:20]} {pr.get('confidence',0):.2f}"
               ~~~~~~~~~~~~^^^^^
TypeError: 'float' object is not subscriptable

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes

================================================================================
MODEL: rtdetr_l_drone_finetuned
================================================================================
prediction rows: 7218

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating rtdetr_l_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/rtdetr_l_drone_finetuned_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics/summary_by_model.csv
Wrote 1 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/plots

Summary by model:
              model_name         model_type  iou_threshold  n_target_present  n_distractor_only recall  tp  fn mean_best_iou  false_positive_image_rate  fp_count                                                                note
rtdetr_l_drone_finetuned ultralytics_rtdetr           0.25                 0                180   None   0   0          None                        1.0      7218 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']
rtdetr_l_drone_finetuned ultralytics_rtdetr           0.50                 0                180   None   0   0          None                        1.0      7218 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']

----- live output ended -----
Return code: 0
Elapsed time: 0.0 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 154, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 124, in main
    label = f"{pr['prompt'][:20]} {pr.get('confidence',0):.2f}"
               ~~~~~~~~~~~~^^^^^
TypeError: 'float' object is not subscriptable

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes

Subset summary written to: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics/summary_by_model_with_eval_subset.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset
0,grounding_dino,grounding_dino,0.25,0,180,NaN,0,0,NaN,1.0,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only
1,grounding_dino,grounding_dino,0.50,0,180,NaN,0,0,NaN,1.0,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only
2,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,0,180,NaN,0,0,NaN,1.0,7218,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only
3,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,0,180,NaN,0,0,NaN,1.0,7218,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only
4,yolo11n_drone_finetuned,ultralytics_yolo,0.25,0,62,NaN,0,0,NaN,1.0,107,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only
5,yolo11n_drone_finetuned,ultralytics_yolo,0.50,0,62,NaN,0,0,NaN,1.0,107,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only

####################################################################################################
METRICS FOR EVAL SUBSET: test_mixed
####################################################################################################

================================================================================
MODEL: grounding_dino
================================================================================
prediction rows: 1999

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating grounding_dino from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/grounding_dino_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics/summary_by_model.csv
Wrote 5 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/plots

Summary by model:
    model_name     model_type  iou_threshold  n_target_present  n_distractor_only   recall  tp  fn  mean_best_iou false_positive_image_rate  fp_count                                                      note
grounding_dino grounding_dino           0.25               180                  0 0.450000  81  99       0.291645                      None         0 Open-vocabulary drone prompts; boxes count as drone-like.
grounding_dino grounding_dino           0.50               180                  0 0.372222  67 113       0.258512                      None         0 Open-vocabulary drone prompts; boxes count as drone-like.

----- live output ended -----
Return code: 0
Elapsed time: 0.1 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Saved: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/visualizations/grounding_dino_prediction_qa.png
Legend: green=GT drone, orange=predictions

----- live output ended -----
Return code: 0
Elapsed time: 0.0 minutes

================================================================================
MODEL: yolo11n_drone_finetuned
================================================================================
prediction rows: 382

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating yolo11n_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/yolo11n_drone_finetuned_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics/summary_by_model.csv
Wrote 6 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/plots

Summary by model:
             model_name       model_type  iou_threshold  n_target_present  n_distractor_only   recall  tp  fn  mean_best_iou false_positive_image_rate  fp_count                                                                note
yolo11n_drone_finetuned ultralytics_yolo           0.25               157                  0 0.828025 130  27       0.604162                      None         0 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']
yolo11n_drone_finetuned ultralytics_yolo           0.50               157                  0 0.777070 122  35       0.584071                      None         0 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']

----- live output ended -----
Return code: 0
Elapsed time: 0.1 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 154, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 124, in main
    label = f"{pr['prompt'][:20]} {pr.get('confidence',0):.2f}"
               ~~~~~~~~~~~~^^^^^
TypeError: 'float' object is not subscriptable

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes

================================================================================
MODEL: rtdetr_l_drone_finetuned
================================================================================
prediction rows: 6401

Running:
/usr/bin/python3 scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating rtdetr_l_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/rtdetr_l_drone_finetuned_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics/summary_by_model.csv
Wrote 7 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/plots

Summary by model:
              model_name         model_type  iou_threshold  n_target_present  n_distractor_only   recall  tp  fn  mean_best_iou false_positive_image_rate  fp_count                                                                note
rtdetr_l_drone_finetuned ultralytics_rtdetr           0.25               180                  0 0.827778 149  31       0.559633                      None         0 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']
rtdetr_l_drone_finetuned ultralytics_rtdetr           0.50               180                  0 0.694444 125  55       0.508564                      None         0 Fine-tuned / drone-capable checkpoint; drone_like_classes=['drone']

----- live output ended -----
Return code: 0
Elapsed time: 0.1 minutes

Running:
/usr/bin/python3 scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 154, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py", line 124, in main
    label = f"{pr['prompt'][:20]} {pr.get('confidence',0):.2f}"
               ~~~~~~~~~~~~^^^^^
TypeError: 'float' object is not subscriptable

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes

Subset summary written to: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics/summary_by_model_with_eval_subset.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset
0,grounding_dino,grounding_dino,0.25,180,0,0.450000,81,99,0.291645,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor
1,grounding_dino,grounding_dino,0.50,180,0,0.372222,67,113,0.258512,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor
2,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,180,0,0.827778,149,31,0.559633,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor
3,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,180,0,0.694444,125,55,0.508564,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor
4,yolo11n_drone_finetuned,ultralytics_yolo,0.25,157,0,0.828025,130,27,0.604162,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor
5,yolo11n_drone_finetuned,ultralytics_yolo,0.50,157,0,0.777070,122,35,0.584071,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor

Combined final-clean summary written to:
/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/combined_metrics/summary_by_model_by_eval_subset.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset
0,grounding_dino,grounding_dino,0.25,180,0,0.622222,112,68,0.399236,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_drone_positive,synthetic_drone_positive
1,grounding_dino,grounding_dino,0.50,180,0,0.538889,97,83,0.366148,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_drone_positive,synthetic_drone_positive
2,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,180,0,0.816667,147,33,0.547084,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive
3,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,180,0,0.700000,126,54,0.502650,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive
4,yolo11n_drone_finetuned,ultralytics_yolo,0.25,143,0,0.916084,131,12,0.677089,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive
5,yolo11n_drone_finetuned,ultralytics_yolo,0.50,143,0,0.860140,123,20,0.654746,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive
6,grounding_dino,grounding_dino,0.25,0,180,NaN,0,0,NaN,1.0,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only
7,grounding_dino,grounding_dino,0.50,0,180,NaN,0,0,NaN,1.0,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only
8,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,0,180,NaN,0,0,NaN,1.0,7218,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only
9,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,0,180,NaN,0,0,NaN,1.0,7218,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only
10,yolo11n_drone_finetuned,ultralytics_yolo,0.25,0,62,NaN,0,0,NaN,1.0,107,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only
11,yolo11n_drone_finetuned,ultralytics_yolo,0.50,0,62,NaN,0,0,NaN,1.0,107,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only
12,grounding_dino,grounding_dino,0.25,180,0,0.450000,81,99,0.291645,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor
13,grounding_dino,grounding_dino,0.50,180,0,0.372222,67,113,0.258512,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor
14,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,180,0,0.827778,149,31,0.559633,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor
15,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,180,0,0.694444,125,55,0.508564,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor
16,yolo11n_drone_finetuned,ultralytics_yolo,0.25,157,0,0.828025,130,27,0.604162,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor
17,yolo11n_drone_finetuned,ultralytics_yolo,0.50,157,0,0.777070,122,35,0.584071,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor

Recall pivot:

eval_subset                             test_drone_positive  test_mixed
model_name               iou_threshold
grounding_dino           0.25                      0.622222    0.450000
                         0.50                      0.538889    0.372222
rtdetr_l_drone_finetuned 0.25                      0.816667    0.827778
                         0.50                      0.700000    0.694444
yolo11n_drone_finetuned  0.25                      0.916084    0.828025
                         0.50                      0.860140    0.777070

FP count pivot:

eval_subset                             test_drone_positive  \
model_name               iou_threshold
grounding_dino           0.25                             0
                         0.50                             0
rtdetr_l_drone_finetuned 0.25                             0
                         0.50                             0
yolo11n_drone_finetuned  0.25                             0
                         0.50                             0

eval_subset                             test_hard_negative  test_mixed
model_name               iou_threshold
grounding_dino           0.25                         1873           0
                         0.50                         1873           0
rtdetr_l_drone_finetuned 0.25                         7218           0
                         0.50                         7218           0
yolo11n_drone_finetuned  0.25                          107           0
                         0.50                          107           0

In [ ]:
#quick diagnostic for YOLO evaluator reports
import pandas as pd
from pathlib import Path

for eval_name, job in EVAL_JOBS.items():
    print("\n", eval_name)
    meta = pd.read_csv(job["dataset_root"] / "metadata.csv")
    print("metadata rows:", len(meta))
    print("metadata target_present:", int(meta["target_present"].astype(bool).sum()))
    print("metadata subset counts:")
    print(meta["subset"].value_counts())

    pred_dir = job["output_root"] / "predictions"
    for model in ["grounding_dino", "yolo11n_drone_finetuned", "rtdetr_l_drone_finetuned"]:
        pred_csv = pred_dir / f"{model}_predictions.csv"
        if pred_csv.exists():
            pred = pd.read_csv(pred_csv)
            if "image_id" in pred.columns:
                print(model, "prediction rows:", len(pred), "unique images:", pred["image_id"].nunique())
            elif "filename" in pred.columns:
                print(model, "prediction rows:", len(pred), "unique filenames:", pred["filename"].nunique())
            else:
                print(model, "prediction rows:", len(pred), "columns:", list(pred.columns))
        else:
            print(model, "missing")

 test_drone_positive
metadata rows: 180
metadata target_present: 180
metadata subset counts:
subset
synthetic_drone_positive    180
Name: count, dtype: int64
grounding_dino prediction rows: 2061 unique images: 180
yolo11n_drone_finetuned prediction rows: 313 unique images: 143
rtdetr_l_drone_finetuned prediction rows: 5862 unique images: 180

 test_hard_negative
metadata rows: 180
metadata target_present: 0
metadata subset counts:
subset
synthetic_distractor_only    180
Name: count, dtype: int64
grounding_dino prediction rows: 1873 unique images: 180
yolo11n_drone_finetuned prediction rows: 107 unique images: 62
rtdetr_l_drone_finetuned prediction rows: 7218 unique images: 180

 test_mixed
metadata rows: 180
metadata target_present: 180
metadata subset counts:
subset
synthetic_drone_plus_distractor    180
Name: count, dtype: int64
grounding_dino prediction rows: 1999 unique images: 180
yolo11n_drone_finetuned prediction rows: 382 unique images: 157
rtdetr_l_drone_finetuned prediction rows: 6401 unique images: 180

In [ ]:
#Create corrected final metrics table
import pandas as pd
import numpy as np
from pathlib import Path

combined_path = EVAL_OUTPUT_ROOT / "combined_metrics" / "summary_by_model_by_eval_subset.csv"
df = pd.read_csv(combined_path)

def pred_unique_images(pred_csv):
    if not Path(pred_csv).exists():
        return 0
    p = pd.read_csv(pred_csv)
    if len(p) == 0:
        return 0
    if "image_id" in p.columns:
        return p["image_id"].nunique()
    if "filename" in p.columns:
        return p["filename"].nunique()
    return 0

corrected_rows = []

for _, row in df.iterrows():
    row = row.copy()
    eval_name = row["eval_subset"]
    model = row["model_name"]
    job = EVAL_JOBS[eval_name]

    meta = pd.read_csv(job["dataset_root"] / "metadata.csv")
    total_images = len(meta)
    total_targets = int(meta["target_present"].astype(bool).sum())
    total_hardneg = int((meta["subset"] == "synthetic_distractor_only").sum())

    pred_csv = job["output_root"] / "predictions" / f"{model}_predictions.csv"
    unique_pred_images = pred_unique_images(pred_csv)

    row["metadata_total_images"] = total_images
    row["prediction_unique_images"] = unique_pred_images

    if total_targets > 0:
        # Positive or mixed subset.
        row["n_target_present"] = total_targets
        row["fn"] = total_targets - int(row["tp"])
        row["recall"] = int(row["tp"]) / total_targets
        row["false_positive_image_rate"] = np.nan
        row["fp_count"] = 0
    else:
        # Hard negative subset.
        row["n_target_present"] = 0
        row["n_distractor_only"] = total_hardneg
        row["recall"] = np.nan
        row["tp"] = 0
        row["fn"] = 0
        row["mean_best_iou"] = np.nan
        row["false_positive_image_rate"] = unique_pred_images / total_hardneg if total_hardneg else np.nan
        # fp_count from evaluator is still useful: number of false-positive boxes.
        row["fp_count"] = int(row["fp_count"])

    corrected_rows.append(row)

corrected = pd.DataFrame(corrected_rows)

corrected = corrected.sort_values(
    ["eval_subset", "model_name", "iou_threshold"]
).reset_index(drop=True)

corrected_path = EVAL_OUTPUT_ROOT / "combined_metrics" / "summary_by_model_by_eval_subset_CORRECTED.csv"
corrected.to_csv(corrected_path, index=False)

print("Corrected summary written to:")
print(corrected_path)

display(corrected)

print("\nCorrected recall pivot:")
display(corrected.pivot_table(
    index=["model_name", "iou_threshold"],
    columns="eval_subset",
    values="recall",
    aggfunc="first",
))

print("\nCorrected false-positive image-rate pivot:")
display(corrected.pivot_table(
    index=["model_name", "iou_threshold"],
    columns="eval_subset",
    values="false_positive_image_rate",
    aggfunc="first",
))

print("\nFP count pivot:")
display(corrected.pivot_table(
    index=["model_name", "iou_threshold"],
    columns="eval_subset",
    values="fp_count",
    aggfunc="first",
))

Corrected summary written to:
/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/combined_metrics/summary_by_model_by_eval_subset_CORRECTED.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset,metadata_total_images,prediction_unique_images
0,grounding_dino,grounding_dino,0.25,180,0,0.622222,112,68,0.399236,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_drone_positive,synthetic_drone_positive,180,180
1,grounding_dino,grounding_dino,0.50,180,0,0.538889,97,83,0.366148,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_drone_positive,synthetic_drone_positive,180,180
2,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,180,0,0.816667,147,33,0.547084,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive,180,180
3,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,180,0,0.700000,126,54,0.502650,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive,180,180
4,yolo11n_drone_finetuned,ultralytics_yolo,0.25,180,0,0.727778,131,49,0.677089,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive,180,143
5,yolo11n_drone_finetuned,ultralytics_yolo,0.50,180,0,0.683333,123,57,0.654746,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive,180,143
6,grounding_dino,grounding_dino,0.25,0,180,NaN,0,0,NaN,1.000000,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only,180,180
7,grounding_dino,grounding_dino,0.50,0,180,NaN,0,0,NaN,1.000000,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only,180,180
8,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,0,180,NaN,0,0,NaN,1.000000,7218,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only,180,180
9,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,0,180,NaN,0,0,NaN,1.000000,7218,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only,180,180
10,yolo11n_drone_finetuned,ultralytics_yolo,0.25,0,180,NaN,0,0,NaN,0.344444,107,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only,180,62
11,yolo11n_drone_finetuned,ultralytics_yolo,0.50,0,180,NaN,0,0,NaN,0.344444,107,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only,180,62
12,grounding_dino,grounding_dino,0.25,180,0,0.450000,81,99,0.291645,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor,180,180
13,grounding_dino,grounding_dino,0.50,180,0,0.372222,67,113,0.258512,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor,180,180
14,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,180,0,0.827778,149,31,0.559633,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor,180,180
15,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,180,0,0.694444,125,55,0.508564,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor,180,180
16,yolo11n_drone_finetuned,ultralytics_yolo,0.25,180,0,0.722222,130,50,0.604162,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor,180,157
17,yolo11n_drone_finetuned,ultralytics_yolo,0.50,180,0,0.677778,122,58,0.584071,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor,180,157

Corrected recall pivot:

eval_subset                             test_drone_positive  test_mixed
model_name               iou_threshold
grounding_dino           0.25                      0.622222    0.450000
                         0.50                      0.538889    0.372222
rtdetr_l_drone_finetuned 0.25                      0.816667    0.827778
                         0.50                      0.700000    0.694444
yolo11n_drone_finetuned  0.25                      0.727778    0.722222
                         0.50                      0.683333    0.677778

Corrected false-positive image-rate pivot:

eval_subset                             test_hard_negative
model_name               iou_threshold
grounding_dino           0.25                     1.000000
                         0.50                     1.000000
rtdetr_l_drone_finetuned 0.25                     1.000000
                         0.50                     1.000000
yolo11n_drone_finetuned  0.25                     0.344444
                         0.50                     0.344444

FP count pivot:

eval_subset                             test_drone_positive  \
model_name               iou_threshold
grounding_dino           0.25                             0
                         0.50                             0
rtdetr_l_drone_finetuned 0.25                             0
                         0.50                             0
yolo11n_drone_finetuned  0.25                             0
                         0.50                             0

eval_subset                             test_hard_negative  test_mixed
model_name               iou_threshold
grounding_dino           0.25                         1873           0
                         0.50                         1873           0
rtdetr_l_drone_finetuned 0.25                         7218           0
                         0.50                         7218           0
yolo11n_drone_finetuned  0.25                          107           0
                         0.50                          107           0

In [ ]:
# 15) Correct final-clean metrics denominators
# Run this AFTER Cell 14.
# It creates:
# summary_by_model_by_eval_subset_CORRECTED.csv

import pandas as pd
import numpy as np
from pathlib import Path

combined_path = EVAL_OUTPUT_ROOT / "combined_metrics" / "summary_by_model_by_eval_subset.csv"
print("Reading original combined metrics:")
print(combined_path)
print("Exists:", combined_path.exists())

if not combined_path.exists():
    raise FileNotFoundError(
        "summary_by_model_by_eval_subset.csv does not exist. "
        "Run Cell 14 first."
    )

df = pd.read_csv(combined_path)

def get_unique_pred_images(pred_csv):
    pred_csv = Path(pred_csv)
    if not pred_csv.exists() or pred_csv.stat().st_size == 0:
        return 0

    pred = pd.read_csv(pred_csv)

    if len(pred) == 0:
        return 0

    if "image_id" in pred.columns:
        return pred["image_id"].nunique()

    if "filename" in pred.columns:
        return pred["filename"].nunique()

    return 0

corrected_rows = []

for _, row in df.iterrows():
    row = row.copy()

    eval_name = row["eval_subset"]
    model_name = row["model_name"]

    job = EVAL_JOBS[eval_name]

    metadata_path = job["dataset_root"] / "metadata.csv"
    metadata_df = pd.read_csv(metadata_path)

    total_images = len(metadata_df)
    total_target_present = int(metadata_df["target_present"].astype(bool).sum())

    if "subset" in metadata_df.columns:
        total_hard_negative = int((metadata_df["subset"] == "synthetic_distractor_only").sum())
    else:
        total_hard_negative = 0

    pred_csv = job["output_root"] / "predictions" / f"{model_name}_predictions.csv"
    unique_pred_images = get_unique_pred_images(pred_csv)

    row["metadata_total_images"] = total_images
    row["prediction_unique_images"] = unique_pred_images

    # Positive or mixed subset: recall denominator must be ALL target-present images,
    # not only images that had at least one prediction.
    if total_target_present > 0:
        tp = int(row["tp"])
        row["n_target_present"] = total_target_present
        row["fn"] = total_target_present - tp
        row["recall"] = tp / total_target_present
        row["false_positive_image_rate"] = np.nan
        row["fp_count"] = 0

    # Hard-negative subset: no recall. FP image rate denominator must be ALL hard-negative images.
    else:
        row["n_target_present"] = 0
        row["n_distractor_only"] = total_hard_negative
        row["tp"] = 0
        row["fn"] = 0
        row["recall"] = np.nan
        row["mean_best_iou"] = np.nan
        row["false_positive_image_rate"] = (
            unique_pred_images / total_hard_negative
            if total_hard_negative > 0
            else np.nan
        )
        row["fp_count"] = int(row["fp_count"])

    corrected_rows.append(row)

corrected = pd.DataFrame(corrected_rows)

corrected = corrected.sort_values(
    ["eval_subset", "model_name", "iou_threshold"]
).reset_index(drop=True)

corrected_path = EVAL_OUTPUT_ROOT / "combined_metrics" / "summary_by_model_by_eval_subset_CORRECTED.csv"
corrected.to_csv(corrected_path, index=False)

print("\n✅ Corrected summary written to:")
print(corrected_path)

display(corrected)

print("\nCorrected recall pivot:")
display(corrected.pivot_table(
    index=["model_name", "iou_threshold"],
    columns="eval_subset",
    values="recall",
    aggfunc="first",
))

print("\nCorrected false-positive image-rate pivot:")
display(corrected.pivot_table(
    index=["model_name", "iou_threshold"],
    columns="eval_subset",
    values="false_positive_image_rate",
    aggfunc="first",
))

print("\nFP count pivot:")
display(corrected.pivot_table(
    index=["model_name", "iou_threshold"],
    columns="eval_subset",
    values="fp_count",
    aggfunc="first",
))

Reading original combined metrics:
/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/combined_metrics/summary_by_model_by_eval_subset.csv
Exists: True

✅ Corrected summary written to:
/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/combined_metrics/summary_by_model_by_eval_subset_CORRECTED.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset,metadata_total_images,prediction_unique_images
0,grounding_dino,grounding_dino,0.25,180,0,0.622222,112,68,0.399236,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_drone_positive,synthetic_drone_positive,180,180
1,grounding_dino,grounding_dino,0.50,180,0,0.538889,97,83,0.366148,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_drone_positive,synthetic_drone_positive,180,180
2,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,180,0,0.816667,147,33,0.547084,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive,180,180
3,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,180,0,0.700000,126,54,0.502650,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive,180,180
4,yolo11n_drone_finetuned,ultralytics_yolo,0.25,180,0,0.727778,131,49,0.677089,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive,180,143
5,yolo11n_drone_finetuned,ultralytics_yolo,0.50,180,0,0.683333,123,57,0.654746,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_drone_positive,synthetic_drone_positive,180,143
6,grounding_dino,grounding_dino,0.25,0,180,NaN,0,0,NaN,1.000000,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only,180,180
7,grounding_dino,grounding_dino,0.50,0,180,NaN,0,0,NaN,1.000000,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only,180,180
8,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,0,180,NaN,0,0,NaN,1.000000,7218,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only,180,180
9,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,0,180,NaN,0,0,NaN,1.000000,7218,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only,180,180
10,yolo11n_drone_finetuned,ultralytics_yolo,0.25,0,180,NaN,0,0,NaN,0.344444,107,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only,180,62
11,yolo11n_drone_finetuned,ultralytics_yolo,0.50,0,180,NaN,0,0,NaN,0.344444,107,Fine-tuned / drone-capable checkpoint; drone_l...,test_hard_negative,synthetic_distractor_only,180,62
12,grounding_dino,grounding_dino,0.25,180,0,0.450000,81,99,0.291645,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor,180,180
13,grounding_dino,grounding_dino,0.50,180,0,0.372222,67,113,0.258512,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor,180,180
14,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.25,180,0,0.827778,149,31,0.559633,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor,180,180
15,rtdetr_l_drone_finetuned,ultralytics_rtdetr,0.50,180,0,0.694444,125,55,0.508564,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor,180,180
16,yolo11n_drone_finetuned,ultralytics_yolo,0.25,180,0,0.722222,130,50,0.604162,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor,180,157
17,yolo11n_drone_finetuned,ultralytics_yolo,0.50,180,0,0.677778,122,58,0.584071,NaN,0,Fine-tuned / drone-capable checkpoint; drone_l...,test_mixed,synthetic_drone_plus_distractor,180,157

Corrected recall pivot:

eval_subset                             test_drone_positive  test_mixed
model_name               iou_threshold
grounding_dino           0.25                      0.622222    0.450000
                         0.50                      0.538889    0.372222
rtdetr_l_drone_finetuned 0.25                      0.816667    0.827778
                         0.50                      0.700000    0.694444
yolo11n_drone_finetuned  0.25                      0.727778    0.722222
                         0.50                      0.683333    0.677778

Corrected false-positive image-rate pivot:

eval_subset                             test_hard_negative
model_name               iou_threshold
grounding_dino           0.25                     1.000000
                         0.50                     1.000000
rtdetr_l_drone_finetuned 0.25                     1.000000
                         0.50                     1.000000
yolo11n_drone_finetuned  0.25                     0.344444
                         0.50                     0.344444

FP count pivot:

eval_subset                             test_drone_positive  \
model_name               iou_threshold
grounding_dino           0.25                             0
                         0.50                             0
rtdetr_l_drone_finetuned 0.25                             0
                         0.50                             0
yolo11n_drone_finetuned  0.25                             0
                         0.50                             0

eval_subset                             test_hard_negative  test_mixed
model_name               iou_threshold
grounding_dino           0.25                         1873           0
                         0.50                         1873           0
rtdetr_l_drone_finetuned 0.25                         7218           0
                         0.50                         7218           0
yolo11n_drone_finetuned  0.25                          107           0
                         0.50                          107           0

In [ ]:
from pathlib import Path
import py_compile

viz_py = PROJECT_ROOT / "code/code/scripts/eval/visualize_predictions.py"
print("Patching:", viz_py)

text = viz_py.read_text()
lines = text.splitlines()

# Find the loop start and the draw function start
start_idx = -1
for i, line in enumerate(lines):
    if "for _, pr in pred_groups.get(image_id, pd.DataFrame()).iterrows():" in line:
        start_idx = i + 1
        break

end_idx = -1
if start_idx != -1:
    for i in range(start_idx, len(lines)):
        if "_draw_xyxy(" in lines[i]:
            end_idx = i
            break

if start_idx != -1 and end_idx != -1:
    new_block = """            prompt = pr.get("prompt", "")
            if not isinstance(prompt, str) or str(prompt).lower() == "nan":
                prompt = pr.get("pred_class_name", "")
            if not isinstance(prompt, str) or str(prompt).lower() == "nan":
                prompt = pr.get("class_name", "")
            if not isinstance(prompt, str) or str(prompt).lower() == "nan":
                prompt = "pred"

            confidence = pr.get("confidence", 0)
            try:
                confidence = float(confidence)
            except Exception:
                confidence = 0.0
            label = f'{str(prompt)[:20]} {confidence:.2f}'"""

    new_lines = lines[:start_idx] + new_block.splitlines() + lines[end_idx:]
    viz_py.write_text("\n".join(new_lines) + "\n")
    print("\u2705 Found the block and replaced it cleanly.")
else:
    print("\u274c Could not find the boundaries for the replacement.")

# Verify syntax after patching
try:
    py_compile.compile(str(viz_py), doraise=True)
    print("\u2705 Syntax verification successful.")
except Exception as e:
    print(f"\u274c Syntax error still exists: {e}")

Patching: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/visualize_predictions.py
✅ Found the block and replaced it cleanly.
✅ Syntax verification successful.

In [ ]:
# # 14) Metrics + prediction QA by held-out evaluation subset
# # Robust version:
# # - deletes stale empty/corrupt metric files before each eval
# # - supports run_command() returning either int or CompletedProcess
# # - keeps going if one model fails

# import pandas as pd
# from pathlib import Path
# import sys

# models = [
#     "grounding_dino",
#     "yolo11n_drone_finetuned",
#     "rtdetr_l_drone_finetuned",
# ]

# def get_return_code(result):
#     """Support both streaming run_command returning int and subprocess.CompletedProcess."""
#     if isinstance(result, int):
#         return result
#     return getattr(result, "returncode", result)

# def safe_read_csv(path):
#     """Read CSV safely; return empty DataFrame if missing/empty/corrupt."""
#     path = Path(path)
#     if not path.exists():
#         return pd.DataFrame()
#     try:
#         if path.stat().st_size == 0:
#             print("WARNING: CSV exists but is empty:", path)
#             return pd.DataFrame()
#         return pd.read_csv(path)
#     except Exception as e:
#         print("WARNING: failed reading CSV:", path)
#         print("Reason:", repr(e))
#         return pd.DataFrame()

# all_rows = []

# for eval_name, job in EVAL_JOBS.items():
#     print("\n" + "#" * 100)
#     print("METRICS FOR EVAL SUBSET:", eval_name)
#     print("#" * 100)

#     metadata_df = pd.read_csv(job["dataset_root"] / "metadata.csv")

#     n_target_present = (
#         int(metadata_df["target_present"].astype(bool).sum())
#         if "target_present" in metadata_df.columns
#         else 0
#     )

#     n_distractor_only = (
#         int((metadata_df["subset"] == "synthetic_distractor_only").sum())
#         if "subset" in metadata_df.columns
#         else 0
#     )

#     pred_dir = job["output_root"] / "predictions"
#     metrics_dir = job["output_root"] / "metrics"
#     metrics_dir.mkdir(parents=True, exist_ok=True)

#     # Remove stale/corrupt summary files before this subset's evaluation.
#     stale_files = [
#         metrics_dir / "summary_by_model.csv",
#         metrics_dir / "summary_by_model_with_eval_subset.csv",
#     ]
#     for stale in stale_files:
#         if stale.exists():
#             print("Removing stale metrics file:", stale)
#             stale.unlink()

#     subset_rows = []

#     for model in models:
#         pred_csv = pred_dir / f"{model}_predictions.csv"

#         print("\n" + "=" * 80)
#         print("MODEL:", model)
#         print("=" * 80)

#         if not pred_csv.is_file():
#             print("SKIP missing prediction file:", pred_csv)
#             continue

#         pred_df = safe_read_csv(pred_csv)
#         print("prediction rows:", len(pred_df))

#         if len(pred_df) == 0:
#             print("Empty prediction CSV. Adding zero-detection metrics instead of crashing.")

#             for iou_thr in [0.25, 0.50]:
#                 subset_rows.append({
#                     "eval_subset": eval_name,
#                     "source_subset": job["subset"],
#                     "model_name": model,
#                     "model_type": "empty_or_underconfident",
#                     "iou_threshold": iou_thr,
#                     "n_target_present": n_target_present,
#                     "n_distractor_only": n_distractor_only,
#                     "recall": 0.0,
#                     "tp": 0,
#                     "fn": n_target_present,
#                     "mean_best_iou": 0.0,
#                     "false_positive_image_rate": 0.0,
#                     "fp_count": 0,
#                     "note": "No predictions at configured inference threshold; likely undertrained or threshold too high.",
#                 })

#             continue

#         # Important: delete summary before each model too, because evaluator appends/updates it.
#         summary_path = metrics_dir / "summary_by_model.csv"
#         if summary_path.exists():
#             print("Removing previous model summary before eval:", summary_path)
#             summary_path.unlink()

#         result = run_command([
#             sys.executable,
#             "-u",
#             "code/code/scripts/eval/evaluate_detector_predictions.py",
#             "--config", str(job["config"]),
#             "--predictions", str(pred_csv),
#             "--project-root", str(PROJECT_ROOT),
#         ], check=False)

#         rc = get_return_code(result)

#         if rc == 0:
#             summary_df = safe_read_csv(summary_path)

#             if len(summary_df):
#                 summary_df["eval_subset"] = eval_name
#                 summary_df["source_subset"] = job["subset"]
#                 subset_rows.extend(summary_df.to_dict("records"))
#             else:
#                 print("WARNING: evaluator succeeded but summary is missing/empty:", summary_path)

#         else:
#             print("Evaluation failed for this model; see output above.")
#             continue

#         # Visualization / prediction QA. Non-critical.
#         viz_result = run_command([
#             sys.executable,
#             "-u",
#             "code/code/scripts/eval/visualize_predictions.py",
#             "--config", str(job["config"]),
#             "--predictions", str(pred_csv),
#             "--project-root", str(PROJECT_ROOT),
#             "--num-samples", "12",
#         ], check=False)

#         viz_rc = get_return_code(viz_result)
#         if viz_rc != 0:
#             print("WARNING: visualization failed, but metrics may still be valid.")

#     subset_summary = pd.DataFrame(subset_rows)

#     if len(subset_summary):
#         subset_summary = subset_summary.drop_duplicates(
#             subset=["eval_subset", "model_name", "iou_threshold"],
#             keep="last",
#         ).sort_values(["eval_subset", "model_name", "iou_threshold"]).reset_index(drop=True)

#     subset_summary_path = metrics_dir / "summary_by_model_with_eval_subset.csv"
#     subset_summary.to_csv(subset_summary_path, index=False)

#     print("\nSubset summary written to:", subset_summary_path)
#     display(subset_summary)

#     all_rows.extend(subset_summary.to_dict("records"))

# combined_summary = pd.DataFrame(all_rows)

# if len(combined_summary):
#     combined_summary = combined_summary.drop_duplicates(
#         subset=["eval_subset", "model_name", "iou_threshold"],
#         keep="last",
#     ).sort_values(["eval_subset", "model_name", "iou_threshold"]).reset_index(drop=True)

# combined_metrics_dir = EVAL_OUTPUT_ROOT / "combined_metrics"
# combined_metrics_dir.mkdir(parents=True, exist_ok=True)

# combined_path = combined_metrics_dir / "summary_by_model_by_eval_subset.csv"
# combined_summary.to_csv(combined_path, index=False)

# print("\nCombined final-clean summary written to:")
# print(combined_path)
# display(combined_summary)

# if len(combined_summary):
#     print("\nRecall pivot:")
#     display(combined_summary.pivot_table(
#         index=["model_name", "iou_threshold"],
#         columns="eval_subset",
#         values="recall",
#         aggfunc="first",
#     ))

#     print("\nFP count pivot:")
#     display(combined_summary.pivot_table(
#         index=["model_name", "iou_threshold"],
#         columns="eval_subset",
#         values="fp_count",
#         aggfunc="first",
#     ))

#     print("\nFalse-positive image-rate pivot:")
#     display(combined_summary.pivot_table(
#         index=["model_name", "iou_threshold"],
#         columns="eval_subset",
#         values="false_positive_image_rate",
#         aggfunc="first",
#     ))

####################################################################################################
METRICS FOR EVAL SUBSET: test_drone_positive
####################################################################################################
Removing stale metrics file: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/metrics/summary_by_model.csv

================================================================================
MODEL: grounding_dino
================================================================================
prediction rows: 2061

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating grounding_dino from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/grounding_dino_predictions.csv
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 110, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 76, in main
    save_evaluation_outputs(outputs, cfg.metrics_dir(), model_name)
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py", line 339, in save_evaluation_outputs
    old = pd.read_csv(win_long_path(path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes
Evaluation failed for this model; see output above.

================================================================================
MODEL: yolo11n_drone_finetuned
================================================================================
prediction rows: 313

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating yolo11n_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/yolo11n_drone_finetuned_predictions.csv
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 110, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 76, in main
    save_evaluation_outputs(outputs, cfg.metrics_dir(), model_name)
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py", line 339, in save_evaluation_outputs
    old = pd.read_csv(win_long_path(path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes
Evaluation failed for this model; see output above.

================================================================================
MODEL: rtdetr_l_drone_finetuned
================================================================================
prediction rows: 5862

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_drone_positive.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating rtdetr_l_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/predictions/rtdetr_l_drone_finetuned_predictions.csv
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 110, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 76, in main
    save_evaluation_outputs(outputs, cfg.metrics_dir(), model_name)
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py", line 339, in save_evaluation_outputs
    old = pd.read_csv(win_long_path(path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes
Evaluation failed for this model; see output above.

Subset summary written to: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_drone_positive/metrics/summary_by_model_with_eval_subset.csv

Empty DataFrame
Columns: []
Index: []

####################################################################################################
METRICS FOR EVAL SUBSET: test_hard_negative
####################################################################################################

================================================================================
MODEL: grounding_dino
================================================================================
prediction rows: 1873

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating grounding_dino from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/grounding_dino_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics/summary_by_model.csv
Wrote 1 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/plots

Summary by model:
    model_name     model_type  iou_threshold  n_target_present  n_distractor_only recall  tp  fn mean_best_iou  false_positive_image_rate  fp_count                                                      note
grounding_dino grounding_dino           0.25                 0                180   None   0   0          None                        1.0      1873 Open-vocabulary drone prompts; boxes count as drone-like.
grounding_dino grounding_dino           0.50                 0                180   None   0   0          None                        1.0      1873 Open-vocabulary drone prompts; boxes count as drone-like.

----- live output ended -----
Return code: 0
Elapsed time: 0.0 minutes

Running:
/usr/bin/python3 -u scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Saved: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/visualizations/grounding_dino_prediction_qa.png
Legend: green=GT drone, orange=predictions

----- live output ended -----
Return code: 0
Elapsed time: 0.1 minutes

================================================================================
MODEL: yolo11n_drone_finetuned
================================================================================
prediction rows: 107
Removing previous model summary before eval: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics/summary_by_model.csv

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating yolo11n_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/yolo11n_drone_finetuned_predictions.csv
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 110, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 76, in main
    save_evaluation_outputs(outputs, cfg.metrics_dir(), model_name)
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py", line 339, in save_evaluation_outputs
    old = pd.read_csv(win_long_path(path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes
Evaluation failed for this model; see output above.

================================================================================
MODEL: rtdetr_l_drone_finetuned
================================================================================
prediction rows: 7218

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_hard_negative.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating rtdetr_l_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/predictions/rtdetr_l_drone_finetuned_predictions.csv
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 110, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 76, in main
    save_evaluation_outputs(outputs, cfg.metrics_dir(), model_name)
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py", line 339, in save_evaluation_outputs
    old = pd.read_csv(win_long_path(path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes
Evaluation failed for this model; see output above.

Subset summary written to: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_hard_negative/metrics/summary_by_model_with_eval_subset.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset
0,grounding_dino,grounding_dino,0.25,0,180,NaN,0,0,NaN,1.0,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only
1,grounding_dino,grounding_dino,0.50,0,180,NaN,0,0,NaN,1.0,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only

####################################################################################################
METRICS FOR EVAL SUBSET: test_mixed
####################################################################################################

================================================================================
MODEL: grounding_dino
================================================================================
prediction rows: 1999

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating grounding_dino from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/grounding_dino_predictions.csv

Wrote summary: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics/summary_by_model.csv
Wrote 5 plots to /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/plots

Summary by model:
    model_name     model_type  iou_threshold  n_target_present  n_distractor_only   recall  tp  fn  mean_best_iou false_positive_image_rate  fp_count                                                      note
grounding_dino grounding_dino           0.25               180                  0 0.450000  81  99       0.291645                      None         0 Open-vocabulary drone prompts; boxes count as drone-like.
grounding_dino grounding_dino           0.50               180                  0 0.372222  67 113       0.258512                      None         0 Open-vocabulary drone prompts; boxes count as drone-like.

----- live output ended -----
Return code: 0
Elapsed time: 2.5 minutes

Running:
/usr/bin/python3 -u scripts/eval/visualize_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/grounding_dino_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification' --num-samples 12

----- live output starts -----
Saved: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/visualizations/grounding_dino_prediction_qa.png
Legend: green=GT drone, orange=predictions

----- live output ended -----
Return code: 0
Elapsed time: 0.0 minutes

================================================================================
MODEL: yolo11n_drone_finetuned
================================================================================
prediction rows: 382
Removing previous model summary before eval: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics/summary_by_model.csv

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/yolo11n_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating yolo11n_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/yolo11n_drone_finetuned_predictions.csv
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 110, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 76, in main
    save_evaluation_outputs(outputs, cfg.metrics_dir(), model_name)
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py", line 339, in save_evaluation_outputs
    old = pd.read_csv(win_long_path(path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes
Evaluation failed for this model; see output above.

================================================================================
MODEL: rtdetr_l_drone_finetuned
================================================================================
prediction rows: 6401

Running:
/usr/bin/python3 -u scripts/eval/evaluate_detector_predictions.py --config '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/configs/generated_eval_subsets/eval_test_mixed.yaml' --predictions '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/rtdetr_l_drone_finetuned_predictions.csv' --project-root '/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification'

----- live output starts -----
Evaluating rtdetr_l_drone_finetuned from /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/predictions/rtdetr_l_drone_finetuned_predictions.csv
Traceback (most recent call last):
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 110, in <module>
    main()
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/scripts/eval/evaluate_detector_predictions.py", line 76, in main
    save_evaluation_outputs(outputs, cfg.metrics_dir(), model_name)
  File "/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/src/drone_stress/detector_eval/metrics.py", line 339, in save_evaluation_outputs
    old = pd.read_csv(win_long_path(path))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

----- live output ended -----
Return code: 1
Elapsed time: 0.0 minutes
Evaluation failed for this model; see output above.

Subset summary written to: /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/test_mixed/metrics/summary_by_model_with_eval_subset.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset
0,grounding_dino,grounding_dino,0.25,180,0,0.450000,81,99,0.291645,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor
1,grounding_dino,grounding_dino,0.50,180,0,0.372222,67,113,0.258512,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor

Combined final-clean summary written to:
/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/evaluation/final_clean_full_curated_v1/combined_metrics/summary_by_model_by_eval_subset.csv

,model_name,model_type,iou_threshold,n_target_present,n_distractor_only,recall,tp,fn,mean_best_iou,false_positive_image_rate,fp_count,note,eval_subset,source_subset
0,grounding_dino,grounding_dino,0.25,0,180,NaN,0,0,NaN,1.0,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only
1,grounding_dino,grounding_dino,0.50,0,180,NaN,0,0,NaN,1.0,1873,Open-vocabulary drone prompts; boxes count as ...,test_hard_negative,synthetic_distractor_only
2,grounding_dino,grounding_dino,0.25,180,0,0.450000,81,99,0.291645,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor
3,grounding_dino,grounding_dino,0.50,180,0,0.372222,67,113,0.258512,NaN,0,Open-vocabulary drone prompts; boxes count as ...,test_mixed,synthetic_drone_plus_distractor

Recall pivot:

eval_subset                   test_mixed
model_name     iou_threshold
grounding_dino 0.25             0.450000
               0.50             0.372222

FP count pivot:

eval_subset                   test_hard_negative  test_mixed
model_name     iou_threshold
grounding_dino 0.25                         1873           0
               0.50                         1873           0

False-positive image-rate pivot:

eval_subset                   test_hard_negative
model_name     iou_threshold
grounding_dino 0.25                          1.0
               0.50                          1.0

In [ ]:
# 15) Optional: YOLO confidence diagnostic on one positive test image
# Use this if YOLO predictions are empty or unexpectedly weak.

from pathlib import Path

try:
    from ultralytics import YOLO

    weights = PROJECT_ROOT / "outputs/training/yolo" / YOLO_RUN_NAME / "weights/best.pt"

    # Pick first test positive image if available.
    pos_root = EVAL_JOBS["test_drone_positive"]["dataset_root"]
    pos_meta = pd.read_csv(pos_root / "metadata.csv")
    sample_image_id = pos_meta["image_id"].astype(str).iloc[0]
    image = pos_root / "images" / sample_image_id

    print("weights exists:", weights.exists(), weights)
    print("sample image exists:", image.exists(), image)

    if weights.exists() and image.exists():
        model = YOLO(str(weights))
        for conf in [0.25, 0.10, 0.05, 0.02, 0.01, 0.005, 0.001]:
            results = model.predict(
                source=str(image),
                conf=conf,
                imgsz=640,
                device=0,
                verbose=False,
                max_det=300,
            )
            n_boxes = len(results[0].boxes)
            if n_boxes:
                confs = results[0].boxes.conf.cpu().numpy()
                print(f"conf={conf}: boxes={n_boxes}, max_conf={confs.max():.5f}, min_conf={confs.min():.5f}")
            else:
                print(f"conf={conf}: boxes=0")

except Exception as e:
    print("YOLO confidence diagnostic failed:", repr(e))

weights exists: True /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/outputs/training/yolo/yolo11n_drone_colab/weights/best.pt
sample image exists: True /content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/data/evaluation/final_clean_full_curated_v1/test_drone_positive/images/img_001276.png
conf=0.25: boxes=2, max_conf=0.45179, min_conf=0.28569
conf=0.1: boxes=2, max_conf=0.45179, min_conf=0.28569
conf=0.05: boxes=3, max_conf=0.45179, min_conf=0.06056
conf=0.02: boxes=4, max_conf=0.45179, min_conf=0.02124
conf=0.01: boxes=5, max_conf=0.45179, min_conf=0.01401
conf=0.005: boxes=7, max_conf=0.45179, min_conf=0.00538
conf=0.001: boxes=20, max_conf=0.45179, min_conf=0.00103

In [ ]:
# 16) Save final-clean results zip to Drive
results_dir = PROJECT_ROOT / "drone_colab_results"
results_dir.mkdir(parents=True, exist_ok=True)

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
zip_base = results_dir / f"drone_colab_final_clean_results_{timestamp}"

archive_path = shutil.make_archive(
    base_name=str(zip_base),
    format="zip",
    root_dir=str(EVAL_OUTPUT_ROOT),
)

print("Saved results archive:")
print(archive_path)

Saved results archive:
/content/drive/MyDrive/Synthetic Stress Testing for Skyborne Drone Identification/drone_colab_results/drone_colab_final_clean_results_20260628_172157.zip

## Notes

This notebook implements the final clean subset evaluation protocol:

- Train YOLO/RT-DETR on the **train split containing all three conditions**:
  - `synthetic_drone_positive`
  - `synthetic_distractor_only`
  - `synthetic_drone_plus_distractor`

- Evaluate GroundingDINO, YOLO, and RT-DETR separately on held-out test subsets:
  - `test_drone_positive`
  - `test_hard_negative`
  - `test_mixed`

- The main final table is saved to:

`outputs/evaluation/final_clean_full_curated_v1/combined_metrics/summary_by_model_by_eval_subset.csv`

Scientific interpretation:

- For `test_drone_positive` and `test_mixed`, recall and IoU metrics are meaningful.
- For `test_hard_negative`, recall is not meaningful because no drone exists. Focus on false-positive image rate and FP count.
- Hard negatives are included in training as negative examples, not as a standalone detector-training dataset.